### PR TITLE
Support for Node 14

### PR DESCRIPTION
**Pull request by calebmshafer**
Node 14 has been moved to LTS as of [last week](https://nodejs.org/en/about/releases/).  Updated the versions iModel.js supports to include it and continue to support `>10.16` and 12.x.

I did put a note in the NextVersion.md warning about dropping support for Node 10 at iModel.js 3.0 due to it leaving LTS around that time, 2021-04-30.

Updated node-sass from 4.13.1 to 4.14.1 in order to support Node 14. However, with node-sass being deprecated shortly we should start investigating moving away from it and using dart sass instead (package name is `sass`).  It's a purely js implementation, instead of containing a native portion, which would be nice for compatibility reasons.

### CODE REVIEW

**Review by ColinKerr — APPROVED** [review]

**Review by grigasp — APPROVED** [review]

**Review by pmconne — APPROVED** [review]

**Review by kabentley — COMMENTED** [review]
I would like to update the minimum version to 10.17. Napi version 5 requires it and my other PR requires Napi V5.

**Comment by calebmshafer** [comment]
Debugged the issue with the core-full-stack-tests with @wgoehrig and we figured out it was due to "null" now being treated as undefined in Node 14.  We haven't been generating a coverage report for these tests in a while due to how slow the sourcemaps are and routinely running out of memory.

There are a couple items that we need to circle back to;

1. Make sure certa handles the lack of sourcemaps more gracefully.  It currently will fail because `null` is set by istanbul and that previously wasn't causing the crash but due to Node changing how that works it is technically a failure
1. Revisit enabling coverage for core-full-stack-tests.  They've been disabled for months through the `certa.json` and `webpack.config.js`, although we were passing the `--cover` flag to certa on the cli which is unnecessary and what lead to this issue.

**Review by wgoehrig — APPROVED** [review]

**Comment by calebmshafer** [comment]
Due to the Mac failures, I'll probably hold off on this update for 2.9.0 to give us some more time to figure out what's going on.

**Comment by calebmshafer** [comment]
I made a mess of the history here so I'll open a new PR once I have the corresponding native changes ready.

**Pull request closed without merging**
