### PR TITLE
Bumped to latest dotenv

### PR DESCRIPTION
**Pull request by SpencerWBarnes**
@types/dotenv removed since dotenv now includes its own type definitions

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Comment by aruniverse** [comment]
Copying my comment over from the other pr so it doesnt get lost, https://github.com/imodeljs/imodeljs/pull/1964#issuecomment-892012738 

Might i add we look into using dotenv-flow?
We could then commit default env vars to the .env and track in vcs, and then just override accordingly in a .env.*.local file.

I know dotenv recommend not commit .env files but dotenv-flow suggest otherwise, and this is the approach taken by main big names, like react-scripts and others.

I guess if we wanted to pick this up, we could do it in this pr or another.

**Review by DanEastBentley — APPROVED** [review]

**Comment by calebmshafer** [comment]
@aruniverse it has pretty low usage compared to the other two packages. I guess only people using react-scripts would be using it?

I'd want to do it in a separate PR as well.

**Review by aruniverse — APPROVED** [review]

**Comment by SpencerWBarnes** [comment]
@mergifyio update

**Comment by calebmshafer** [comment]
@Mergifyio update

**Pull request merged**
