### PR TITLE
Update imodel-bridges.md

### PR DESCRIPTION
**Pull request by timlawrence-bentley**
Changed all instances of "bridge" to "connector"

### CODE REVIEW

**Review by pmconne — COMMENTED** [review]
A whole bunch of other .md files in /docs/ continue to use the term "bridge" - are there plans to clean those up too (and rename imodel-bridges.md)?

**Comment by timlawrence-bentley** [comment]
Hi Paul,

I wasn’t aware of that, but I could do that as well. I only made these changes because I somehow ended up on that page. The rename would be good too, but currently well beyond my github abilities.

Tim

**Comment by pmconne** [comment]
> Hi Paul, I wasn’t aware of that, but I could do that as well. I only made these changes because I somehow ended up on that page. The rename would be good too, but currently well beyond my github abilities. Tim

Thanks Tim. If you're willing to straighten out our terminology once and for all that'd be excellent.

Renaming on cmd line is easy: `git mv imodel-bridges.md imodel-connectors.md`.

**Comment by timlawrence-bentley** [comment]
closing this pull request and putting in a new one with hopefully across the board changes to replace bridges with connectors

**Pull request closed without merging**
