### PR TITLE
Fix missing presentation-common dependency in extension-cli

### PR DESCRIPTION
**Pull request by paulius-valiunas**

### CODE REVIEW

**Comment by calebmshafer** [comment]
@paulius-valiunas why did this regression happen in the first place?  Did something change in the dependent packages to cause it?

**Comment by paulius-valiunas** [comment]
@calebmshafer I'm not sure, I'm guessing `fetch` was polyfilled in some other package and I just didn't notice it. I switched to explicitly using the `cross-fetch` implementation instead of relying on a happy coincidence so that should be fine now.

**Review by pmconne — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Comment by calebmshafer** [comment]
I reverted the change to add cross-fetch since it caused issues when included on the client side and once I added the presentation-common dependency I no longer can reproduce the issue.

**Comment by calebmshafer** [comment]
@Mergifyio backport release/2.15.x

**Comment by wgoehrig** [comment]
what's up with  tools/backend-webpack/bin/backend-webpack-tools.js?  Why does the diff show it as an empty file?

**Pull request merged**
