### PR TITLE
Fix silhouettes 2

### PR DESCRIPTION
**Pull request by MarcNeely**
Added a tolerance on silhouette determination to make the flickering of some silhouettes more stable.

### CODE REVIEW

**Comment by pmconne** [comment]
Cylinders display all their silhouettes when viewed roughly head-on - expected?
image

**Comment by pmconne** [comment]
I guess the new behavior is preferable to previous:
image

**Comment by MarcNeely** [comment]
Can’t figure out how to reply to you on Github.  I think the picture is so big, maybe it’s covering up the button to reply?

Anyhow, yes, I saw that the old way has some problems when looking down a pipe & this actually makes it worse, but it fixes the ones which were winking in & out for the most part.

David & I looked at this problem you brought up & have not come up with a way to fix it yet.

Marc

**Comment by pmconne** [comment]
> Can’t figure out how to reply to you on Github.

You can only reply to comments linked to a line of source code; otherwise you can use "quote reply" to include context. If you reply via email please edit the comment to omit personal info like email address etc.

> David & I looked at this problem you brought up & have not come up with a way to fix it yet.

Separate issue I think; anyway at least the "extra" silhouettes are more consistent than they were before.

**Review by pmconne — APPROVED** [review]

**Pull request merged**
