### PR TITLE
Disable importSorter.sortOnBeforeSave

### PR DESCRIPTION
**Pull request by paulius-valiunas**

### CODE REVIEW

**Comment by kabentley** [comment]
i don't think we should remove this. It is very helpful. Instead, remove sortOnBeforeSave

**Comment by miniant-git** [comment]
Could we also remove the following?
```json
"eslint.codeAction.disableRuleComment": {
  "location": "sameLine"
},
```

This seems to me more like a personal preference and in many situations, I think having disable rule comments on a separate line to be more advantageous. It follows our standard comment style, keeps code width within 120 columns and is much easier to remove (Ctrl+L, Backspace), which I do quite often to see if the disable comment is still required.

Those who wish to have it on same line can easily add this configuration to their user settings.

**Comment by paulius-valiunas** [comment]
> i don't think we should remove this. It is very helpful. Instead, remove sortOnBeforeSave

I've been thinking about how we use this extension and I'd like to replace as much of it as possible with eslint rules.

For this particular case, there is an eslint rule called `@typescript-eslint/no-unused-vars` that does the same thing.

If I disable `sortOnBeforeSave`, I'd still want to disable this one too just to reduce duplicate functionality between this extension and eslint.

I'm not a fan of disabling sort on save, I think most people will just forget this extension exists. It's like having an eslint rule set to "warn" but even less noticeable since it doesn't show yellow squiggles. I initially wasn't sure what to think of this extension and interpreted it as a way to at least partly enforce neatly sorted imports in our code base, but if you have a different idea, I can disable it, that's your call.

**Comment by roluk** [comment]
Could we also remove the following?
```json
"eslint.codeAction.disableRuleComment": {
  "location": "sameLine"
},
```

This seems to me more like a personal preference and in many situations, I think having disable rule comments on a separate line to be more advantageous. It follows our standard comment style, keeps code width within 120 columns and is much easier to remove (Ctrl+L, Backspace), which I do quite often to see if the disable comment is still required.

Those who wish to have it on same line can easily add this configuration to their user settings.

**Comment by paulius-valiunas** [comment]
> 
> 
> Could we also remove the following?
> 
> ```json
> "eslint.codeAction.disableRuleComment": {
>   "location": "sameLine"
> },
> ```
> 
> This seems to me more like a personal preference and in many situations, I think having disable rule comments on a separate line to be more advantageous. It follows our standard comment style, keeps code width within 120 columns and is much easier to remove (Ctrl+L, Backspace), which I do quite often to see if the disable comment is still required.
> 
> Those who wish to have it on same line can easily add this configuration to their user settings.

I applied this as a fix to some other comments not being detected. I think it was either API extractor and our docs comments, or istanbul ignore comments. Something had to be directly above a line or one of them wouldn't be detected.

**Comment by paulius-valiunas** [comment]
you know what, Robert, I think you're right on this one. For the rare case where it creates a conflict, you can always move the comment to the same line yourself.

**Comment by kabentley** [comment]
> > i don't think we should remove this. It is very helpful. Instead, remove sortOnBeforeSave
> 
> I've been thinking about how we use this extension and I'd like to replace as much of it as possible with eslint rules.
> 
> For this particular case, there is an eslint rule called `@typescript-eslint/no-unused-vars` that does the same thing.
> 
> If I disable `sortOnBeforeSave`, I'd still want to disable this one too just to reduce duplicate functionality between this extension and eslint.
> 
> I'm not a fan of disabling sort on save, I think most people will just forget this extension exists. It's like having an eslint rule set to "warn" but even less noticeable since it doesn't show yellow squiggles. I initially wasn't sure what to think of this extension and interpreted it as a way to at least partly enforce neatly sorted imports in our code base, but if you have a different idea, I can disable it, that's your call.

Having `sortOnBeforeSave` eliminates the possibility that anyone could have a required order-of-imports dependency.

**Comment by paulius-valiunas** [comment]
OK, point taken.
I'm still tempted to fully replace this extension with eslint rules and remove it in the future to reduce overlap. There's really not that much functionality missing even with our existing eslint config. Any thoughts on that?

**Comment by kabentley** [comment]
> OK, point taken.
> I'm still tempted to fully replace this extension with eslint rules and remove it in the future to reduce overlap. There's really not that much functionality missing even with our existing eslint config. Any thoughts on that?

I'd far rather it be handled by eslint rather than the VSCode extension because not everyone (e.g. @pmconne) uses VSCode. Does the eslint rule no-unused-vars really remove unused entries from import statements?

**Comment by paulius-valiunas** [comment]
I just checked that again, and it appears that it's not the eslint rule, but rather VSCode itself providing the fix through the `ctrl+.` shortcut (eslint suggestions appear in the same place, that's why I was confused). Here's an example:
image
If you're not using VSCode, eslint will just make you fix it yourself:
```
D:\code\iModelJs\imodeljs\core\backend\src\IModelHost.ts(11,13): error @typescript-eslint/no-unused-vars : 'semver' is defined but never used. Allowed unused vars must match /^_/u.
D:\code\iModelJs\imodeljs\core\backend\src\IModelHost.ts(16,74): error @typescript-eslint/no-unused-vars : 'RpcConfiguration' is defined but never used. Allowed unused vars must match /^_/u.
D:\code\iModelJs\imodeljs\core\backend\src\IModelHost.ts(16,92): error @typescript-eslint/no-unused-vars : 'SerializedRpcRequest' is defined but never used. Allowed unused vars must match /^_/u.
D:\code\iModelJs\imodeljs\core\backend\src\IModelHost.ts(18,44): error @typescript-eslint/no-unused-vars : 'AuthorizedClientRequestContext' is defined but never used. Allowed unused vars must match /^_/u.D:\code\iModelJs\imodeljs\core\backend\src\IModelHost.ts(18,96): error @typescript-eslint/no-unused-vars : 'UserInfo' is defined but never used. Allowed unused vars must match /^_/u.
D:\code\iModelJs\imodeljs\core\backend\src\IModelHost.ts(30,10): error @typescript-eslint/no-unused-vars : 'IModelJsFs' is defined but never used. Allowed unused vars must match /^_/u.
```
Either way, it still does the same as the extension, i.e. fixes the issue only if you're using VSCode.

It wouldn't be too hard to make the rule auto-fixable so that VSCode isn't required for this, but I'd have to either "fork" the rule (or copy/paste the code into our repository) or convince someone at `@typescript-eslint` to merge it into their master.

**Comment by kabentley** [comment]
> It wouldn't be too hard to make the rule auto-fixable so that VSCode isn't required for this, but I'd have to either "fork" the rule (or copy/paste the code into our repository) or convince someone at `@typescript-eslint` to merge it into their master.

Why not just leave the "remove unused" rule on for the extension? What prompted this PR? I presume the problem was that it was removing some imports from .tsx files (that's what i saw)? If we don't force it to run on those files every time save, then it isn't a problem.

BTW, does the eslint rule complain about unsorted imports?

**Comment by pmconne** [comment]
> BTW, does the eslint rule complain about unsorted imports?

Yes, the linter will complain about those.

**Comment by paulius-valiunas** [comment]
Yeah, I got a complaint about tsx files, especially if you're using autosave. If the extension doesn't run on save, leaving it on doesn't really hurt. I thought eslint did the same thing so I wanted to disable it just to reduce duplication, but since I discovered it's a separate VSCode action, I guess it makes sense to add it back to reduce the number of separate actions you have to take to fix your imports.

When it comes to sorting imports in eslint, it's a bit more complicated since there are different rules for:

- Sorting individual imports, such as swapping `BackendIpc` and `SerializedRpcRequest` in the above screenshot if they're misplaced. We have an eslint rule for that part, which by the way could cause conflicts with this extension due to different handling of aliases.
- Sorting entire import statements, such as swapping the `imodelhub-client` line with the `imodeljs-common` line. There is an existing eslint rule for that, but we're not using it. Back when I had it enabled in a draft PR, it was the slowest rule of all by a wide margin. I then decided I'd write my own because it doesn't have to be that complicated, but it's still not done since it's not at the highest priority.

The import sorter extension covers both of these, which is pretty much the only reason why I'm still keeping it.

**Review by kabentley — APPROVED** [review]

**Pull request merged**
