### PR TITLE
@bentley/imodeljs-native@2.19.10 (#2092) (#2030)

### PR DESCRIPTION
**Pull request by MichaelBelousov**
* use nativeDb single schema export instead of dumping all of them
* remove alpha toXmlString method

Co-authored-by: Michael Belousov <MichaelBelousov@users.noreply.github.com>

### CODE REVIEW

**Comment by calebmshafer** [comment]
@MichaelBelousov you'll want to include the patch native addon in this PR.

**Comment by MichaelBelousov** [comment]
> @MichaelBelousov you'll want to include the patch native addon in this PR.

@calebmshafer do you mean bump the patch version of the native addon?

**Comment by calebmshafer** [comment]
@MichaelBelousov yes, the new patch version needs to be released with the native changes you made and then in this PR you would update the dependency to that new version.

**Review by ColinKerr — APPROVED** [review]

**Comment by calebmshafer** [comment]
@MichaelBelousov you'll probably need this PR as well to consume the new addon, https://github.com/imodeljs/imodeljs/pull/2030.  @khanaffan backported those changes as well.

**Review by calebmshafer — APPROVED** [review]

**Review by wgoehrig — APPROVED** [review]

**Review by bsteinbk — APPROVED** [review]

**Pull request merged**
