### PR TITLE
Version application data properties

### PR DESCRIPTION
**Pull request by amikoliunas**

### CODE REVIEW

**Comment by amikoliunas** [comment]
azp run

**Review by Animagne — APPROVED** [review]

**Comment by calebmshafer** [comment]
@amikoliunas @Animagne does this need to be backported?

**Comment by amikoliunas** [comment]
> @amikoliunas @Animagne does this need to be backported?

I think so, Diego needs it for consumption reporting.

**Comment by calebmshafer** [comment]
@diegopinate can you confirm the backport need?

**Comment by diegopinate** [comment]
> @amikoliunas @Animagne does this need to be backported?

@calebmshafer, yes, we would need this asap for the agent to use

**Comment by calebmshafer** [comment]
@Mergifyio backport release/2.19.x

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
