### PR TITLE
Remove .only from tests.

### PR DESCRIPTION
**Pull request by pmconne**
It is extremely concerning that a PR can unwittingly disable broad swathes of tests. It keeps happening.

### CODE REVIEW

**Review by paulius-valiunas — APPROVED** [review]
oops... I thought we had an automatic check for that?

**Comment by pmconne** [comment]
@paulius-valiunas I did too. It stopped working a while ago - I don't recall when. Perhaps we lost it when we switched from ADO to GitHub?

**Review by kabentley — APPROVED** [review]

**Comment by paulius-valiunas** [comment]
I'll be more careful in the future. I was too confident in our pipeline 😅

**Comment by calebmshafer** [comment]
I'll take a look today. Maybe it broke during our upgrade to mocha, that's the only thing I can currently think of.

**Comment by pmconne** [comment]
A test failure appears to have snuck through as a result.
```
  1 failing

  1) iModel
       should throw when attempting to re-attach a non-checkpoint snapshot:
     AssertionError: expected undefined not to be undefined
      at expectIModelError (src\test\standalone\IModel.test.ts:52:26)
      at Context.<anonymous> (src\test\standalone\IModel.test.ts:2020:5)
```

**Comment by pmconne** [comment]
@Mergifyio backport imodel02

**Comment by calebmshafer** [comment]
It is an issue with our update to Mocha 8. The newest version does a "fail-fast" check for `.only` so if we forbid the use of `.only`, the tests aren't even run. Prior to v6, the check would come later which allowed us to dynamically check for it in the reporter phase, after all tests have run. I'll work up a PR to change how we handle this...

**Comment by paulius-valiunas** [comment]
I'll close this since now we have #1669

**Pull request closed without merging**
