### PR TITLE
Presentation: Remove `dataProvider` prop from `usePresentationTreeNodeLoader`

### PR DESCRIPTION
**Pull request by roluk**
`dataProvider` was included in `usePresentationTreeNodeLoader` props for testing purposes, but this increases the hook's complexity and adds a possibility for the prop to be misused. Since there is a good alternative that still allows testing this hook fully without requiring `@internal` props, there should be no reason to keep and maintain that extra complexity.

This change uses `sinon.stub` to define `PresentationTreeDataProvider` behavior during tests, and removes internal `dataProvider` props from a number of components.

When switching to using `sinon` stubs, I encountered the following error: `TypeError: Cannot stub non-existent property getFilteredNodePaths`. The error occurred due to `getFilteredNodePaths` being assigned during object's construction rather being defined in the class prototype. Defining this member as a regular function has fixed this error.

The error I encountered above should be enough reason to avoid using this pattern of initializing class methods as variables, because this prevents them from being stubbed in tests.

### CODE REVIEW

**Comment by roluk** [comment]
A bunch of line ending changes have made their way into the commits. I'll remake them and do a force-push.

**Review by grigasp — APPROVED** [review]

**Review by DanEastBentley — APPROVED** [review]

**Comment by aruniverse** [comment]
This was a breaking change that should have been documented imo.
I know it's internal so we probably shouldn't have been using it.
See https://github.com/imodeljs/viewer-components-react/blob/master/packages/tree-widget/src/components/trees/TreeWithRuleset.tsx

**Comment by grigasp** [comment]
> This was a breaking change that should have been documented imo.
> I know it's internal so we probably shouldn't have been using it.
> See https://github.com/imodeljs/viewer-components-react/blob/master/packages/tree-widget/src/components/trees/TreeWithRuleset.tsx

I do not agree - `@internal` clearly states that you shouldn't be using it and I'd like to think that we can break internal APIs anytime. In addition, internal APIs aren't documented to ensure they're not visible to the outside consumers (sadly they're not stripped from declarations), so I believe there's no need to document breaking changes of something that shouldn't be used by anyone in the first place.

Looking at the linked source file, I don't see why it needs a data provider - can you point us to a place where this `TreeWithRuleset` component is used? Thanks.

**Comment by aruniverse** [comment]
> Looking at the linked source file, I don't see why it needs a data provider - can you point us to a place where this `TreeWithRuleset` component is used? Thanks.

I believe this is used in the classification tree used by DR in the building-ui-components package. We'll refactor this pkg for 3.0 and will let you know if we run into any issues.

**Pull request merged**
