### PR TITLE
Add right mouse click for TreeNode

### PR DESCRIPTION
**Pull request by GintV**
Add right mouse click for TreeNode

### CODE REVIEW

**Comment by DanEastBentley** [comment]
You'll need to run "rush extract-api", commit the changed API.md file, then run "rush change", add & commit the change log.

**Comment by GintV** [comment]
> You'll need to run "rush extract-api", commit the changed API.md file, then run "rush change", add & commit the change log.

Strange, `rush extract-api` does not detected any api changes, although I clearly see TreeNodeProps definition in ui-core.api.md... I can change it by hand, if it is the only place that needs the change

**Comment by DanEastBentley** [comment]
In the ui/directory, run "npm run clean", "npm run build", "npm run extract-api". That will probably generate the updated api.md file.

**Comment by GintV** [comment]
It was such a trivial change I forgot to build. Thanks!

**Review by DanEastBentley — APPROVED** [review]

**Comment by DanEastBentley** [comment]
Although the unit tests will pass with this particular change, we usually need to add a unit test with a change. This unit test will test your change in Node.test.tsx:

  it("should call onContextMenu callback when node is right-clicked", () => {
    const callback = sinon.spy();
    const wrapper = mount(<Node label="a" level={0} onContextMenu={callback} />);
    const content = wrapper.find("div.contents");
    content.simulate("contextmenu");
    expect(callback).to.be.calledOnce;
  });

**Comment by calebmshafer** [comment]
@GintV looks like lint is failing, mind updating?  Here's the output,

```
\ui\core\src\test\tree\Node.test.tsx(158,1): error @typescript-eslint/indent : Expected indentation of 2 spaces but found 4.
```

**Comment by GintV** [comment]
@calebmshafer Sorry for late response, I missed your comment in all this mergify clutter... Should be okay now

**Pull request merged**
