### PR TITLE
Correct display of map tiles with depth buffering off

### PR DESCRIPTION
**Pull request by RBBentley**
The logic for rejecting map tiles occluded by the ellipsoid was allowing tile beyond the horizon to be accepted.  With depth buffer turned off (the default) these tiles would display incorrectly.

### CODE REVIEW

**Comment by RBBentley** [comment]
@pmconne This resolves the issue you commented on in the viewing tool PR. https://github.com/imodeljs/imodeljs/commit/8ff49b19166c626d836c725525caf52237b23af9

**Review by pmconne — DISMISSED** [review]
This reduces but does not eliminate the issue. I suppose it can't be eliminated unless you were to reset _maxGlobalScopeFactor after the view zooms back in on a small region. I reckon you don't want to do that.

**Comment by RBBentley** [comment]
> This reduces but does not eliminate the issue. I suppose it can't be eliminated unless you were to reset _maxGlobalScopeFactor after the view zooms back in on a small region. I reckon you don't want to do that.

Can you provide a saved view where this still occurs. I don't think maxGlobalScopeFactor should make any difference here - that only controls loading of the global tiles which should never be selected unless zoomed way out.   There still may be issues as we are relying on display ordering and we only sort by tile depth though.

**Comment by pmconne** [comment]
> Can you provide a saved view where this still occurs. I don't think maxGlobalScopeFactor should make any difference here - that only controls loading of the global tiles which should never be selected unless zoomed way out. There still may be issues as we are relying on display ordering and we only sort by tile depth though.

Yes. To repro you need to zoom out to view the globe then recall this saved view.
image

```
  {
    "_name": "ray",
    "_viewStatePropsString": "{\"viewDefinitionProps\":{\"classFullName\":\"BisCore:SpatialViewDefinition\",\"id\":\"0x3e\",\"jsonProperties\":{\"viewDetails\":{\"gridOrient\":0,\"gridSpaceX\":0.1}},\"code\":{\"spec\":\"0x1c\",\"scope\":\"0x17\",\"value\":\"ray 3\"},\"model\":\"0x17\",\"categorySelectorId\":\"0x41\",\"displayStyleId\":\"0x40\",\"isPrivate\":false,\"description\":\"\",\"cameraOn\":true,\"origin\":[19471.541583935832,-1176.1034296991322,2.096332899253383],\"extents\":[92.30533655275444,45.19677127012551,108.85062968287356],\"angles\":{\"pitch\":-163.09178419607113,\"roll\":-87.77143385106613,\"yaw\":0.6484541920827804},\"camera\":{\"lens\":45.95389015949806,\"focusDist\":108.85062967950289,\"eye\":[19395.338666228312,-1084.1868893173364,20.610677898264576]},\"modelSelectorId\":\"0x3f\"},\"categorySelectorProps\":{\"classFullName\":\"BisCore:CategorySelector\",\"id\":\"0x41\",\"code\":{\"spec\":\"0x8\",\"scope\":\"0x17\",\"value\":\"TPB Building Views - View 1\"},\"model\":\"0x17\",\"categories\":[\"0x18\",\"0x2e\",\"0x30\",\"0x32\",\"0x34\",\"0x36\",\"0x38\",\"0x3a\",\"0x3c\"]},\"displayStyleProps\":{\"classFullName\":\"BisCore:DisplayStyle3d\",\"id\":\"0x40\",\"jsonProperties\":{\"styles\":{\"backgroundMap\":{\"groundBias\":-0.3048,\"providerData\":{\"mapType\":2},\"terrainSettings\":{\"heightOriginMode\":0}},\"environment\":{\"ground\":{\"aboveColor\":32768,\"belowColor\":1262987,\"display\":false,\"elevation\":-0.01},\"sky\":{\"display\":false,\"groundColor\":8228728,\"groundExponent\":4,\"image\":{\"texture\":\"0\",\"type\":0},\"nadirColor\":3880,\"skyColor\":16764303,\"skyExponent\":4,\"zenithColor\":16741686}},\"hline\":{\"transThreshold\":0.3},\"sceneLights\":{\"ambient\":{\"intensity\":29.629629629629623,\"type\":2},\"flash\":{\"intensity\":55.55555555555556,\"type\":3},\"fstop\":2.1997807025909424,\"sun\":{\"intensity\":77625.35688849179,\"type\":1},\"sunDir\":[0.37296549978115007,0.7085963826154433,-0.5989890671099976]},\"viewflags\":{\"backgroundMap\":true,\"noFill\":true,\"renderMode\":6,\"shadows\":true}}},\"code\":{\"spec\":\"0xa\",\"scope\":\"0x17\",\"value\":\"Smooth\"},\"model\":\"0x17\"},\"modelSelectorProps\":{\"classFullName\":\"BisCore:ModelSelector\",\"id\":\"0x3f\",\"code\":{\"spec\":\"0x11\",\"scope\":\"0x17\",\"value\":\"TPB Building Views - View 1\"},\"model\":\"0x17\",\"models\":[\"0x1d\"]}}"
  }
```

**Comment by RBBentley** [comment]
> > Can you provide a saved view where this still occurs. I don't think maxGlobalScopeFactor should make any difference here - that only controls loading of the global tiles which should never be selected unless zoomed way out. There still may be issues as we are relying on display ordering and we only sort by tile depth though.
> 
> Yes. To repro you need to zoom out to view the globe then recall this saved view.
> I think it's only reproducible with depth disabled and/or transparency enabled.
> image
> 
> ```
>   {
>     "_name": "ray",
>     "_viewStatePropsString": "{\"viewDefinitionProps\":{\"classFullName\":\"BisCore:SpatialViewDefinition\",\"id\":\"0x3e\",\"jsonProperties\":{\"viewDetails\":{\"gridOrient\":0,\"gridSpaceX\":0.1}},\"code\":{\"spec\":\"0x1c\",\"scope\":\"0x17\",\"value\":\"ray 3\"},\"model\":\"0x17\",\"categorySelectorId\":\"0x41\",\"displayStyleId\":\"0x40\",\"isPrivate\":false,\"description\":\"\",\"cameraOn\":true,\"origin\":[19471.541583935832,-1176.1034296991322,2.096332899253383],\"extents\":[92.30533655275444,45.19677127012551,108.85062968287356],\"angles\":{\"pitch\":-163.09178419607113,\"roll\":-87.77143385106613,\"yaw\":0.6484541920827804},\"camera\":{\"lens\":45.95389015949806,\"focusDist\":108.85062967950289,\"eye\":[19395.338666228312,-1084.1868893173364,20.610677898264576]},\"modelSelectorId\":\"0x3f\"},\"categorySelectorProps\":{\"classFullName\":\"BisCore:CategorySelector\",\"id\":\"0x41\",\"code\":{\"spec\":\"0x8\",\"scope\":\"0x17\",\"value\":\"TPB Building Views - View 1\"},\"model\":\"0x17\",\"categories\":[\"0x18\",\"0x2e\",\"0x30\",\"0x32\",\"0x34\",\"0x36\",\"0x38\",\"0x3a\",\"0x3c\"]},\"displayStyleProps\":{\"classFullName\":\"BisCore:DisplayStyle3d\",\"id\":\"0x40\",\"jsonProperties\":{\"styles\":{\"backgroundMap\":{\"groundBias\":-0.3048,\"providerData\":{\"mapType\":2},\"terrainSettings\":{\"heightOriginMode\":0}},\"environment\":{\"ground\":{\"aboveColor\":32768,\"belowColor\":1262987,\"display\":false,\"elevation\":-0.01},\"sky\":{\"display\":false,\"groundColor\":8228728,\"groundExponent\":4,\"image\":{\"texture\":\"0\",\"type\":0},\"nadirColor\":3880,\"skyColor\":16764303,\"skyExponent\":4,\"zenithColor\":16741686}},\"hline\":{\"transThreshold\":0.3},\"sceneLights\":{\"ambient\":{\"intensity\":29.629629629629623,\"type\":2},\"flash\":{\"intensity\":55.55555555555556,\"type\":3},\"fstop\":2.1997807025909424,\"sun\":{\"intensity\":77625.35688849179,\"type\":1},\"sunDir\":[0.37296549978115007,0.7085963826154433,-0.5989890671099976]},\"viewflags\":{\"backgroundMap\":true,\"noFill\":true,\"renderMode\":6,\"shadows\":true}}},\"code\":{\"spec\":\"0xa\",\"scope\":\"0x17\",\"value\":\"Smooth\"},\"model\":\"0x17\"},\"modelSelectorProps\":{\"classFullName\":\"BisCore:ModelSelector\",\"id\":\"0x3f\",\"code\":{\"spec\":\"0x11\",\"scope\":\"0x17\",\"value\":\"TPB Building Views - View 1\"},\"model\":\"0x17\",\"models\":[\"0x1d\"]}}"
>   }
> ```

Thanks.    I realize now that the sorting of tiles by depth has not been happening.  I have re-enabled this, please retest.  I am running another imagediffs to verify.

**Comment by RBBentley** [comment]
> > > Can you provide a saved view where this still occurs. I don't think maxGlobalScopeFactor should make any difference here - that only controls loading of the global tiles which should never be selected unless zoomed way out. There still may be issues as we are relying on display ordering and we only sort by tile depth though.
> > 
> > 
> > Yes. To repro you need to zoom out to view the globe then recall this saved view.
> > I think it's only reproducible with depth disabled and/or transparency enabled.
> > image
> > ```
> >   {
> >     "_name": "ray",
> >     "_viewStatePropsString": "{\"viewDefinitionProps\":{\"classFullName\":\"BisCore:SpatialViewDefinition\",\"id\":\"0x3e\",\"jsonProperties\":{\"viewDetails\":{\"gridOrient\":0,\"gridSpaceX\":0.1}},\"code\":{\"spec\":\"0x1c\",\"scope\":\"0x17\",\"value\":\"ray 3\"},\"model\":\"0x17\",\"categorySelectorId\":\"0x41\",\"displayStyleId\":\"0x40\",\"isPrivate\":false,\"description\":\"\",\"cameraOn\":true,\"origin\":[19471.541583935832,-1176.1034296991322,2.096332899253383],\"extents\":[92.30533655275444,45.19677127012551,108.85062968287356],\"angles\":{\"pitch\":-163.09178419607113,\"roll\":-87.77143385106613,\"yaw\":0.6484541920827804},\"camera\":{\"lens\":45.95389015949806,\"focusDist\":108.85062967950289,\"eye\":[19395.338666228312,-1084.1868893173364,20.610677898264576]},\"modelSelectorId\":\"0x3f\"},\"categorySelectorProps\":{\"classFullName\":\"BisCore:CategorySelector\",\"id\":\"0x41\",\"code\":{\"spec\":\"0x8\",\"scope\":\"0x17\",\"value\":\"TPB Building Views - View 1\"},\"model\":\"0x17\",\"categories\":[\"0x18\",\"0x2e\",\"0x30\",\"0x32\",\"0x34\",\"0x36\",\"0x38\",\"0x3a\",\"0x3c\"]},\"displayStyleProps\":{\"classFullName\":\"BisCore:DisplayStyle3d\",\"id\":\"0x40\",\"jsonProperties\":{\"styles\":{\"backgroundMap\":{\"groundBias\":-0.3048,\"providerData\":{\"mapType\":2},\"terrainSettings\":{\"heightOriginMode\":0}},\"environment\":{\"ground\":{\"aboveColor\":32768,\"belowColor\":1262987,\"display\":false,\"elevation\":-0.01},\"sky\":{\"display\":false,\"groundColor\":8228728,\"groundExponent\":4,\"image\":{\"texture\":\"0\",\"type\":0},\"nadirColor\":3880,\"skyColor\":16764303,\"skyExponent\":4,\"zenithColor\":16741686}},\"hline\":{\"transThreshold\":0.3},\"sceneLights\":{\"ambient\":{\"intensity\":29.629629629629623,\"type\":2},\"flash\":{\"intensity\":55.55555555555556,\"type\":3},\"fstop\":2.1997807025909424,\"sun\":{\"intensity\":77625.35688849179,\"type\":1},\"sunDir\":[0.37296549978115007,0.7085963826154433,-0.5989890671099976]},\"viewflags\":{\"backgroundMap\":true,\"noFill\":true,\"renderMode\":6,\"shadows\":true}}},\"code\":{\"spec\":\"0xa\",\"scope\":\"0x17\",\"value\":\"Smooth\"},\"model\":\"0x17\"},\"modelSelectorProps\":{\"classFullName\":\"BisCore:ModelSelector\",\"id\":\"0x3f\",\"code\":{\"spec\":\"0x11\",\"scope\":\"0x17\",\"value\":\"TPB Building Views - View 1\"},\"model\":\"0x17\",\"models\":[\"0x1d\"]}}"
> >   }
> > ```
> 
> Thanks. I realize now that the sorting of tiles by depth has not been happening. I have re-enabled this, please retest. I am running another imagediffs to verify.

I still have some work to do here.... sorting the tiles causes the descendent clipping to misbehave.  I need to study this further.

**Comment by pmconne** [comment]
> I still have some work to do here.... sorting the tiles causes the descendent clipping to misbehave. I need to study this further.

That's the cause of the much-increased flishy-flash of the map tiles when zooming in/out now?

**Comment by RBBentley** [comment]
> > I still have some work to do here.... sorting the tiles causes the descendent clipping to misbehave. I need to study this further.
> 
> That's the cause of the much-increased flishy-flash of the map tiles when zooming in/out now?

Yes -- That was the descendant clipping problem -- Fixed now.

**Review by pmconne — APPROVED** [review]
Looks good. Gonna need to run extract-api in imodeljs-frontend.

**Pull request merged**
