### PR TITLE
Additional transform for Geographic Coordinate Systems

### PR DESCRIPTION
**Pull request by AlainRobertAtBentley**
This PR adds Additional Transforms that are part of the Geographic Coordinate Systems as used in some iModels.

### CODE REVIEW

**Review by pmconne — APPROVED** [review]
Why are `to/fromJSON` and `equals` marked `@intenral`?

**Comment by AlainRobertAtBentley** [comment]
> Why are `to/fromJSON` and `equals` marked `@intenral`?

@pmconne I copied the pattern from the otherGCS classes. And for the other GCS classes I think I was inspired by other classes throughout iModelJS that also marked those as internal. Since the primary intent of the classes are to represent the GCS and not deserialize/serialize explicitely I though it safe to start with the strictest visibility and modify upon need.
I am ready to follow any other guideline you can suggest.

**Comment by pmconne** [comment]
>  I though it safe to start with the strictest visibility and modify upon need.

Many of us have taken that approach under an assumption that we have a good idea of which bits of the API will be useful to others (we don't). We are now in the process of correcting that mistake by promoting an enormous number of internal and alpha APIs to public or beta. Prefer to assign release tags based on their intended usage:
- internal: only our code should ever use it and we will never make it public.
- alpha: experimental; no one else should use it until we've tested it more thoroughly.
- beta: others are encouraged to test it but it's not guaranteed to be stable.
- public: guaranteed to remain stable until the next major version.

**Comment by AlainRobertAtBentley** [comment]
@pmconne Excellent guideline. Since the Future On connector will require the FromJSON() and I am not sure if the code will belong to FutureOn or Bentley I would have needed to promote a bunch of those. I will do on next Pull Request.

**Pull request merged**
