### PR TITLE
Adds finalization stage to push deletion and project extent changes  

### PR DESCRIPTION
**Pull request by zachzhu2016**
Current BridgeRunner does not push deletion and project extent changes for BriefcaseDb. This PR adds an additional stage (Finalization Stage) similar to that of native iModelBridgeFwk to push the changes that must be made at the end of a synchronization job.

### CODE REVIEW

**Comment by jffmarker** [comment]
You removed a public method, updateExistingData, which I think violates our API policy between minor revisions.

**Comment by pmconne** [comment]
> You removed a public method, updateExistingData, which I think violates our API policy between minor revisions.

BridgeRunner is `@beta`. Changes to its API are permitted but should be documented in NextVersion.md with recommended replacement.

**Comment by zachzhu2016** [comment]
I do not see imodel-bridge listed here (https://www.itwinjs.org/reference/). Do we still need to document it somehow? This public method also does not have or need a replacement, it seems supposed to be called by UpdateExistingIModel() only so using it outside of BridgeRunner may not be appropriate (it's simply a method that's marked "public").

**Review by c-macdonald — APPROVED** [review]

**Comment by jffmarker** [comment]
I'd like to de-couple the functional fixes in this PR from the broader documentation topic. We have some cover since it's beta, and we can spin up documentation in a separate PR.

**Comment by williamkbentley** [comment]
You can opt-in to documenting a package by adding it to this file: https://github.com/imodeljs/imodeljs/blob/master/docs/reference/leftNav.md

**Comment by jffmarker** [comment]
I've added a new backlog item to follow up getting this API more exposed.

**Pull request merged**
