### PR TITLE
Azcopy for upload

### PR DESCRIPTION
**Pull request by austeja-bentley**
Added support to use azcopy when applicable during file upload.

### CODE REVIEW

**Comment by calebmshafer** [comment]
@khanaffan are we using your new PR, #365, instead of this one for upload/download via AzCopy?

**Comment by austeja-bentley** [comment]
> @khanaffan are we using your new PR, #365, instead of this one for upload/download via AzCopy?

I think the plan is to merge the #365 and abandon this one.

**Comment by calebmshafer** [comment]
Going to close this in favor of the other PR.

**Review by calebmshafer — APPROVED** [review]
We should setup tests for using AzCopy at some point but that can probably wait until we figure out what to do about @khanaffan's PR.  Otherwise LGTM

**Pull request merged**
