### PR TITLE
Mobile ipc take2

### PR DESCRIPTION
**Pull request by swbsi**

### CODE REVIEW

**Review by pmconne — COMMENTED** [review]
@markschlosseratbentley would you be able to see if this fixes display-test-app on iOS?

**Comment by markschlosseratbentley** [comment]
> @markschlosseratbentley would you be able to see if this fixes display-test-app on iOS?

@pmconne @swbsi Using this branch, the display-test-app iOS app itself crashes...

**Comment by swbsi** [comment]
> > @markschlosseratbentley would you be able to see if this fixes display-test-app on iOS?
> 
> 
> 
> @pmconne @swbsi Using this branch, the display-test-app iOS app itself crashes...

Sounds like I need to build this then...

**Comment by markschlosseratbentley** [comment]
> > > @markschlosseratbentley would you be able to see if this fixes display-test-app on iOS?
> > 
> > 
> > @pmconne @swbsi Using this branch, the display-test-app iOS app itself crashes...
> 
> Sounds like I need to build this then...

@swbsi Let me know if you need me to get more information; It was crashing on app initializing for me and the callstack did not have symbols for me; it was in UIApplicationMain.

**Comment by swbsi** [comment]
> 
> 
> > > > @markschlosseratbentley would you be able to see if this fixes display-test-app on iOS?
> > > 
> > > 
> > > @pmconne @swbsi Using this branch, the display-test-app iOS app itself crashes...
> > 
> > 
> > Sounds like I need to build this then...
> 
> @swbsi Let me know if you need me to get more information; It was crashing on app initializing for me and the callstack did not have symbols for me; it was in UIApplicationMain.

The app works for me now with the changes I just pushed.

**Comment by markschlosseratbentley** [comment]
> > > > > @markschlosseratbentley would you be able to see if this fixes display-test-app on iOS?
> > > > 
> > > > 
> > > > @pmconne @swbsi Using this branch, the display-test-app iOS app itself crashes...
> > > 
> > > 
> > > Sounds like I need to build this then...
> > 
> > 
> > @swbsi Let me know if you need me to get more information; It was crashing on app initializing for me and the callstack did not have symbols for me; it was in UIApplicationMain.
> 
> The app works for me now with the changes I just pushed.

@swbsi I just tested this and verified it works for me now too.

**Review by markschlosseratbentley — APPROVED** [review]

**Review by pmconne — APPROVED** [review]

**Review by wgoehrig — APPROVED** [review]

**Pull request merged**
