### PR TITLE
Create new MapLayerSourceProps interface.

### PR DESCRIPTION
**Pull request by mdastous-bentley**

### CODE REVIEW

**Comment by mdastous-bentley** [comment]
@pmconne How do you feel about this?

**Comment by pmconne** [comment]
Looks like an improvement to me. Need to put a release tag on MapLayerSource.

**Comment by mdastous-bentley** [comment]
@RBBentley maxZoom on MapLayerProps doesnt seem to be of any use?  Should we keep it anyway ?

**Comment by pmconne** [comment]
>  maxZoom on MapLayerProps doesnt seem to be of any use? Should we keep it anyway ?

No; if we ever need it we can put it back.

**Comment by RBBentley** [comment]
> @RBBentley maxZoom on MapLayerProps doesnt seem to be of any use? Should we keep it anyway ?

Sorry - out of office last week -- No need to keep.

**Pull request merged**
