### PR TITLE
Fix 64-bit addition.

### PR DESCRIPTION
**Pull request by pmconne**
If only a language running primarily on 64-bit hardware could efficiently add two 64-bit integers. One can dream...

### CODE REVIEW

**Review by kabentley — APPROVED** [review]

**Comment by pmconne** [comment]
@Mergifyio backport release/2.10.0

**Comment by pmconne** [comment]
@Mergifyio backport release/2.10.x

**Comment by pmconne** [comment]
@Mergifyio backport release/2.11.x

**Comment by pmconne** [comment]
@Mergifyio backport release/2.10.0

**Comment by pmconne** [comment]
@Mergifyio backport release/2.12.x

**Pull request merged**
