### PR TITLE
Do not cache transform for plan projection tile trees.

### PR DESCRIPTION
**Pull request by pmconne**
If an editing operation modifies the model's range, the cached transform will become incorrect. Computing the adjusted transform is trivial; use a scratch Transform to avoid allocations.
[Work item](https://dev.azure.com/bentleycs/iModelTechnologies/_workitems/edit/359550)

### CODE REVIEW

**Review by markschlosseratbentley — APPROVED** [review]
Looks good to me

**Review by RBBentley — APPROVED** [review]
Looks fine.

**Comment by pmconne** [comment]
@Mergifyio backport release/2.12.x

**Comment by calebmshafer** [comment]
@pmconne anything else planned for 2.12.x?  I'll need to run a new patch release prior to the 2.13.0 release.

Also, did this make it into the release/2.13.x branch?

**Comment by pmconne** [comment]
I did not backport to 2.13.x. SYNCHRO Modeler team wanted it in 2.12.x.
SYNCHRO Modeler has a couple of other fixes they want. One they are ok with waiting for 2.13 or 2.14. The other they are currently investigating - some Civil domain decorator.

**Comment by calebmshafer** [comment]
@pmconne okay, no problem with going to 2.12.x, I can do the release, but will need to be in the 2.13.x branch as well to avoid regressing in 2.13.

**Comment by pmconne** [comment]
Right - I will backport to 2.13.x. Hold off on 2.12.x release until SYNCHRO determines if they will have fix for other issue.

**Comment by pmconne** [comment]
@Mergifyio backport release/2.13.x

**Comment by calebmshafer** [comment]
@pmconne sounds good. Just let me know or if you want to run the release :)

**Pull request merged**
