### PR TITLE
UI: Update VirtualizedPropertyGrid styles to accomodate iTwinUI-react components

### PR DESCRIPTION
**Pull request by roluk**
As a part of iTwinUI adoption, existing `ExpandableBlock`, which was used by the property grid, was deprecated and replaced with an equivalent component from `iTwinUI-react` package. This caused a number of layout issues in property grid as the new component has completely different appearance.

This change restyles the property grid to match its new expandable block component and makes it easier to reason about the property grid node layout by eliminating most of the overlap between elements.

### CODE REVIEW

**Review by DanEastBentley — APPROVED** [review]

**Comment by grigasp** [comment]
@DanEastBentley, I think there're more styling problems related to switching to `itwinui-react` components:
- I see some colors have been changed (e.g. blue text in expanded category blocks has become dark grey), but maybe that's fine.
- Information density has substantially dropped, and that's probably not fine:
  - Our test app has several `Select` boxes at the top. Turns out one of them now comes from `itwinui-react` and others from `ui-components`. Here's the difference:
  image
  Notice how the imodel picker has much more padding compared to others that come from `ui-components`.

  - Similar problem in property grid:
  
    Before:
    image

    After:
    image

Is this expected? Is there any way to increase information density in these components?

**Comment by DanEastBentley** [comment]
> @DanEastBentley, I think there're more styling problems related to switching to `itwinui-react` components:
> 
> * I see some colors have been changed (e.g. blue text in expanded category blocks has become dark grey), but maybe that's fine.
> * Information density has substantially dropped, and that's probably not fine:
>   
>   * Our test app has several `Select` boxes at the top. Turns out one of them now comes from `itwinui-react` and others from `ui-components`. Here's the difference:
>     image
>     Notice how the imodel picker has much more padding compared to others that come from `ui-components`.
>   * Similar problem in property grid:
>     Before:
>     image
>     After:
>     image
> 
> Is this expected? Is there any way to increase information density in these components?

**Comment by DanEastBentley** [comment]
@grigasp I put some styling overrides here for apps using ui-framework: https://github.com/imodeljs/imodeljs/blob/ui-components/property-grid-expandable-block/ui/framework/src/ui-framework/configurableui/configurableui.scss#L80. Perhaps there's a better place for these overrides.

**Comment by roluk** [comment]
> 
> 
> @grigasp I put some styling overrides here for apps using ui-framework: https://github.com/imodeljs/imodeljs/blob/ui-components/property-grid-expandable-block/ui/framework/src/ui-framework/configurableui/configurableui.scss#L80. Perhaps there's a better place for these overrides.

Because ui-components lack these style overrides, property grid will have different appearance depending on whether ui-framework is used. Perhaps they should be moved to a different package?

**Review by grigasp — APPROVED** [review]

**Pull request merged**
