### PR TITLE
changing usage of bridges to connectors

### PR DESCRIPTION
**Pull request by timlawrence-bentley**
hopefully this is complete and correct. It should also include file renames in a few instances - if I've done this correctly.

### CODE REVIEW

**Comment by pmconne** [comment]
Thanks for doing this @timlawrence-bentley. Missed a couple spots - I'll fix them up.

**Review by pmconne — APPROVED** [review]

**Comment by pmconne** [comment]
@calebmshafer can you let us know what action is required to get @timlawrence-bentley's PR merged into imodeljs repo?

**Comment by calebmshafer** [comment]
@timlawrence-bentley I queued the iModel.js Docs build [here](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=730195&view=logs&j=00af5505-930d-50dd-3844-b167e8b4bb13&t=e41c6f8c-503e-58b5-343c-c4aff92c601d) and there were a couple broken links.  here's the output

```
Invalid Link: "[overview](../learning/imodel-connectors.md)" in file "learning/writeaconnector"
Invalid Link: "[Transform](../learning/imodel-connectors.md#data-alignment)" in file "learning/writeaconnector"
Invalid Link: "[iModel Connectors]($docs/learning/imodel-connectors.md)" in file "learning/tutorials/create-test-imodel-itwin-sync"
Invalid Link: "[iModel Connectors](../../learning/imodel-connectors.md)" in file "bis/intro/federated-digital-twins"
```

**Comment by calebmshafer** [comment]
> Hi Caleb, The rename of imodel-bridges.md to imodel-connectors.md wasn’t made. Do I need to cancel this PR? Sorry for dumb questions relating to github usage. Tim From: Caleb Shafer <notifications@github.com> Sent: 

@timlawrence-bentley no need to re-open.  I'll kick off a new build now that you pushed the changes.

**Comment by pmconne** [comment]
> I'll kick off a new build now that you pushed the changes.

Is this something only @calebmshafer can do? We like to avoid pestering him when we can.

**Comment by calebmshafer** [comment]
@pmconne it's a painful process right now given the way the association works between GH and ADOps. I manually queue the builds with the necessary variables set to make the association work.

I think I have a way to make it a bit easier that would let someone with write access leaving a comment. I'll kick it off this time and have a PR with the instructions on how members of iModel.js can do it going forward.

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
