### PR TITLE
Download progress does not work using latest AzCopy binary

### PR DESCRIPTION
**Pull request by GintV**
Download progress does not work using latest AzCopy binary
- updated azcopy event args based on latest binary release 10.9.0
- bumped minimum supported azcopy version to 10.9.0
- added ability to cancel downloads when using azcopy

### CODE REVIEW

**Comment by ramanujam-raman** [comment]
@khanaffan  can you take a look?

**Comment by calebmshafer** [comment]
@khanaffan @GintV what's the status of this?  Did you two discuss it outside of this PR?  Last I heard there was some worry about compatibility but didn't catch the full details.

**Comment by GintV** [comment]
@calebmshafer I was out sick for the past week. We discussed this previously and the concern was that this minimum azcopy version update would silently break apps that won't be using latest azcopy version (it will start using http instead of azcopy for downloads). I think main concern was about Design Review Backend and General Purpose Backend. But I think you mentioned that both of them should be using azcopy 10.x on deployment, so in theory it pulls latest version. In that case, we could proceed with this PR as is. If not, I can strip out minimal version update and leave only download cancellation. What do you think @khanaffan?

**Comment by pmconne** [comment]
This PR has been open for 23 days, rebuilding itself every time anyone else merges to master. Closing until it's ready to be merged (set auto-merge when that happens please).

**Pull request closed without merging**
