### PR TITLE
Fix client deps

### PR DESCRIPTION
**Pull request by aruniverse**
Corrected deps in the clients to use dev+peer deps

### CODE REVIEW

**Review by paulius-valiunas — APPROVED** [review]

**Review by calebmshafer — CHANGES_REQUESTED** [review]
I think may of these dependencies are correct today but what may be missing is the `^` in order to allow npm to resolve to the same version as the consuming app is using.

Did you hit a specific issue with one of the packages?

**Comment by wgoehrig** [comment]
> I think may of these dependencies are correct today but what may be missing is the `^` in order to allow npm to resolve to the same version as the consuming app is using.

@calebmshafer Sure that _can_ work, but wouldn't peerDependencies be safer?  By using dependencies, we are pretty reliant on npm to hoist everything correctly, and even when it does, there could be surprising errors...

Take, for example, the case where an app updates the core packages, but not any of these clients.  If the clients only specify dependencies, they'll just be silently installed, and we'll have two copies of packages that we've deemed unsafe to have multiple copies of.  Whereas, with peerDependencies, the developer would see warnings that these packages should probably also be updated.

Granted, for something like @bentley/bentleyjs-core, I don't really see the need to make _that_ a peerDependency - deduping that is obviously ideal, but I don't think having multiple copies of it in node_modules should really break anything, since we should be generally avoiding `instanceof`, right?

But in general, was there a reason we were trying to avoid making these peerDependencies?

**Comment by calebmshafer** [comment]
> > I think may of these dependencies are correct today but what may be missing is the `^` in order to allow npm to resolve to the same version as the consuming app is using.
> 
> @calebmshafer Sure that _can_ work, but wouldn't peerDependencies be safer? By using dependencies, we are pretty reliant on npm to hoist everything correctly, and even when it does, there could be surprising errors...
> 
> Take, for example, the case where an app updates the core packages, but not any of these clients. If the clients only specify dependencies, they'll just be silently installed, and we'll have two copies of packages that we've deemed unsafe to have multiple copies of. Whereas, with peerDependencies, the developer would see warnings that these packages should probably also be updated.
> 
> Granted, for something like @bentley/bentleyjs-core, I don't really see the need to make _that_ a peerDependency - deduping that is obviously ideal, but I don't think having multiple copies of it in node_modules should really break anything, since we should be generally avoiding `instanceof`, right?
> 
> But in general, was there a reason we were trying to avoid making these peerDependencies?

@wgoehrig my reasoning is two-fold, one most of the time hoisting the same version should work and two if these packages don't have any statics that would cause issues or uses of `instanceof`, as you mention, it shouldn't matter if the version is different than the app one.

Otherwise, I would agree using peerDependencies is probably the correct approach. In this case though, I did want to try to be explicit about what packages are required as peerDeps because ideally we'd get to a point where we can limit the number of peer dependencies needed overall when including any of our packages.  It's becoming a bit cumbersome at this..

**Comment by calebmshafer** [comment]
@aruniverse I'm going to abandon this PR.  I'd like to re-visit for 3.0 though as we will be making a change that will hopefully alleviate a lot of these issues.

**Pull request closed without merging**
