### PR TITLE
Fixing broken NativeApp.downloadBriefcase progress callback (2.11.x)

### PR DESCRIPTION
**Pull request by GintV**
Fixing broken NativeApp API (2.11.x)
- fixed progress callback
- fixed download cancellation

### CODE REVIEW

**Review by pmconne — APPROVED** [review]
@kabentley please make sure these fixes survive your refactor.

**Comment by kabentley** [comment]
> @kabentley please make sure these fixes survive your refactor.

I've already fixed this in my PR. See [here](https://github.com/imodeljs/imodeljs/blob/c2a8d8b5f8c6af964bd6c4606e6e02a2f9edf974/core/backend/src/NativeHost.ts#L47-L67)

I'm about the complete that PR, Do you still want to keep this one?

**Comment by pmconne** [comment]
> > @kabentley please make sure these fixes survive your refactor.
> 
> I've already fixed this in my PR. See [here](https://github.com/imodeljs/imodeljs/blob/c2a8d8b5f8c6af964bd6c4606e6e02a2f9edf974/core/backend/src/NativeHost.ts#L47-L67)
Great.

> I'm about the complete that PR, Do you still want to keep this one?
@GintV you encountered this in 2.11, right? Keith's changes will be in 2.13. do you need these fixes backported?

**Comment by GintV** [comment]
@pmconne Yes, we need these fixes in 2.11. Not sure if backporting is possible because there was a lot of refactoring, so that's why I made this PR for 2.11.x only

**Comment by pmconne** [comment]
@GintV I think this will need to be forward-ported to 2.12 too.

**Comment by GintV** [comment]
@pmconne I looked through 2.12 and it should be good there (I borrowed checkAbort from there)

**Review by calebmshafer — APPROVED** [review]

**Comment by GintV** [comment]
@calebmshafer I see that `rush change` is failing with a lot of missing change logs. When I ran `rush change` locally I got prompted to fill in change logs for a lot of packages, but I skipped empty ones because it was comparing with master and it didn't make sense. Should I commit these empty change logs anyway?

**Comment by calebmshafer** [comment]
> @calebmshafer I see that `rush change` is failing with a lot of missing change logs. When I ran `rush change` locally I got prompted to fill in change logs for a lot of packages, but I skipped empty ones because it was comparing with master and it didn't make sense. Should I commit these empty change logs anyway?

@GintV  no need, the build is messed up a bit and wasn't picking up that this PR was targeting the release branch.  Normally you'll want to run rush change like this `rush change -b origin/${targetBranch}` so in this case it would be `rush change -b origin/release/2.11.x`. 

I'm working on getting the build working now.  Hopefully have it done in a few minutes.

**Pull request merged**
