### PR TITLE
Standardize Ipc apis

### PR DESCRIPTION
**Pull request by kabentley**
Discovered while converting iTwin Syncronizer app:

- `IpcInterface` exists only to add a `getVersion` method, which isn't necessary. Instead, change channel name if an Ipc interface changes (e.g. by appending a "-1", "-2", etc. to the channel name).

- Added `removeListener` method to IpcSocket interface. This requires passing `Event` as first argument to `IpcListeners` and not wrapping them with function that strips it.

- expose appropriate methods of `IpcSocket` on `FrontendIpc` and `BackendIpc` as static methods that add the iTwinChannel prefix to channel names.

- change copyright year to 2021.

### CODE REVIEW

**Comment by swbsi** [comment]
An argument in favor of having an IpcInterface type is that it guides consumers to make one...instead of using the untyped send/invoke api directly.

**Comment by kabentley** [comment]
> An argument in favor of having an IpcInterface type is that it guides consumers to make one...instead of using the untyped send/invoke api directly.

yes, but you can't have an empty interface, and the `getVersion` method is not helpful. The class that helps understand what to do is `IpcHandler`, and i think that is where the documentation should lead .

**Comment by swbsi** [comment]
> > An argument in favor of having an IpcInterface type is that it guides consumers to make one...instead of using the untyped send/invoke api directly.
> 
> 
> 
> yes, but you can't have an empty interface, and the `getVersion` method is not helpful. The class that helps understand what to do is `IpcHandler`, and i think that is where the documentation should lead .

True.

Would there be any value in having the interface class so names and versions could be managed over time under source control?

**Comment by swbsi** [comment]
> > > An argument in favor of having an IpcInterface type is that it guides consumers to make one...instead of using the untyped send/invoke api directly.
> > 
> > 
> > 
> > yes, but you can't have an empty interface, and the `getVersion` method is not helpful. The class that helps understand what to do is `IpcHandler`, and i think that is where the documentation should lead .
> 
> True.
> 
> Would there be any value in having the interface class so names and versions could be managed over time under source control?

Never mind...the IpcHandler class has the name.

**Review by swbsi — APPROVED** [review]

**Pull request merged**
