### PR TITLE
Avoid stringify/parse for arguments to native get/update elements and models

### PR DESCRIPTION
**Pull request by kabentley**

### CODE REVIEW

**Review by wgoehrig — CHANGES_REQUESTED** [review]
@kabentley This PR has whitespace-only changes caused by a (recently-fixed) bug in our commit hooks.

Please run the following locally to revert these changes:

```
git co master
git pull
git co <your branch>
git merge master
rush fix-copyrights
```

**Comment by pmconne** [comment]
> @kabentley This PR has whitespace-only changes caused by a (recently-fixed) bug in our commit hooks.
> 
> Please run the following locally to revert these changes:
> 
> ```
> git co master
> git pull
> git co <your branch>
> git merge master
> rush fix-copyrights
> ```

He's merging with imodel02, can't merge master into this branch.

**Comment by wgoehrig** [comment]
@pmconne @kabentley Gah, my bad.  I'm working on fixing this branch now.

**Comment by pmconne** [comment]
> @pmconne @kabentley Gah, my bad. I'm working on fixing this branch now.

I told @kabentley I would fix it up after my addon completes, resulting in master being merged into imodel02.

**Comment by wgoehrig** [comment]
> I told @kabentley I would fix it up after my addon completes, resulting in master being merged into imodel02.

@pmconne whoops - missed this comment.  Just pushed those changes tho - pretty sure there won't be any conflicts with either master or imodel02 tho.

**Comment by pmconne** [comment]
> > I told @kabentley I would fix it up after my addon completes, resulting in master being merged into imodel02.
> 
> @pmconne whoops - missed this comment. Just pushed those changes tho - pretty sure there won't be any conflicts with either master or imodel02 tho.

@wgoehrig can you mark your requested changes as done please?

**Review by wgoehrig — APPROVED** [review]

**Pull request closed without merging**
