### PR TITLE
Floating widget fix

### PR DESCRIPTION
**Pull request by NancyMcCallB**
Remove framework version condition from floatWidget and dockWidget. This caused a problem in the sample showcase.

### CODE REVIEW

**Review by bsteinbk — APPROVED** [review]

**Comment by NancyMcCallB** [comment]
@Mergifyio backport release/2.15.x

**Comment by NancyMcCallB** [comment]
@Mergifyio backport release/2.16.x

**Comment by bsteinbk** [comment]
@Mergifyio backport release/2.15.x

**Comment by bsteinbk** [comment]
@Mergifyio backport release/2.16.x

**Comment by bsteinbk** [comment]
@Mergifyio backport release/2.15.x

**Comment by calebmshafer** [comment]
@Mergifyio backport release/2.16.x

**Comment by NancyMcCallB** [comment]
@Mergifyio backport release/2.15.x

**Pull request merged**
