### PR TITLE
Do not throw exception in BriefcaseManager.downloadBriefcase when the local file already exists AND the briefcase id is unassigned (pull only)

### PR DESCRIPTION
**Pull request by ColinKerr**
This change will keep us from changing the behavior of the briefcase manager right at the end of the 2.x generation.  I am limiting this to the 2.19 branch because it makes sense to have users check to see if a local copy of the iModel exists before calling download briefcase.  So for 3.x adding the exception is a reasonable change.

### CODE REVIEW

**Review by pmconne — CHANGES_REQUESTED** [review]
Can this wait until next week? @kabentley made this change - would be good to get his opinion.

**Comment by kabentley** [comment]
@ColinKerr, no I don’t think you should remove this exception. It should never be possible to download a briefcase on top of an existing file. Anyone counting on that behavior (why?) should fix their code. What app did this break?

(Btw, the reason I added this is that our code to verify the Guids fails and leaves the bc open in this case).

**Comment by ColinKerr** [comment]
> @ColinKerr, no I don’t think you should remove this exception. It should never be possible to download a briefcase on top of an existing file. Anyone counting on that behavior (why?) should fix their code. What app did this break?
> 
> (Btw, the reason I added this is that our code to verify the Guids fails and leaves the bc open in this case).

It will not download the briefcase again.  downloadBriefcase calls downloadCheckpoint which calls verifyCheckpoint.  verifyCheckpoint will poke the file listed in the args and return true if it is the correct iModel.

What is the suggested way to check if a local copy of the briefcase exists?

**Comment by kabentley** [comment]
> It will not download the briefcase again. downloadBriefcase calls downloadCheckpoint which calls verifyCheckpoint. verifyCheckpoint will poke the file listed in the args and return true if it is the correct iModel.

and then leave the file open, causing problems later.

> 
> What is the suggested way to check if a local copy of the briefcase exists?

Either supply and save the filename when downloading, or use `BriefcaseManager.getFileName` if you use the "briefcase cache".

> 
> I noticed this issue when updating the imodel-reporter sample/tool Glen is using

Does that application really acquire briefcases (the name implies readonly)? If not, it should use `BriefcaseIdValue.Unassigned`.

**Comment by ColinKerr** [comment]
> > It will not download the briefcase again. downloadBriefcase calls downloadCheckpoint which calls verifyCheckpoint. verifyCheckpoint will poke the file listed in the args and return true if it is the correct iModel.
> 
> and then leave the file open, causing problems later.
> 

If verifyCheckpoint is leaving the file open it is called in other workflows.  Should we fix it so a failure to verify the GUIDs doesn't leave the briefcase open?

> > What is the suggested way to check if a local copy of the briefcase exists?
> 
> Either supply and save the filename when downloading, or use `BriefcaseManager.getFileName` if you use the "briefcase cache".
> 

OK, I will switch the code to get the file name then check and see if it exists on disk.

> > I noticed this issue when updating the imodel-reporter sample/tool Glen is using
> 
> Does that application really acquire briefcases (the name implies readonly)? If not, it should use `BriefcaseIdValue.Unassigned`.

I supply 0 as the Id which is the same as Unassigned.  I will switch to using the enum.

**Comment by ColinKerr** [comment]
@kabentley I have pushed a change so the exception is not thrown with the briefcase id is unassigned.

**Pull request closed without merging**
