### PR TITLE
Remove tslint from build-tools package

### PR DESCRIPTION
**Pull request by paulius-valiunas**
Removing deprecated linter in preparation for 3.0 release

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by DanEastBentley — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]
Please add something to the NextVersion.md.  We'll need to do some large organization of it later once we have a broader scope of the 3.0 changes but for now just add a line or two.

**Comment by calebmshafer** [comment]
@Mergifyio update

**Comment by aruniverse** [comment]
Will we be pulling this pkg and other build related pkgs out of the core monrorepo in 3.0?

**Comment by calebmshafer** [comment]
@aruniverse I don't know if we'll remove them from the repo but I would like to split the buildology type packages out of the lock step version policies.

**Pull request merged**
