### PR TITLE
Promote lint warnings to errors

### PR DESCRIPTION
**Pull request by paulius-valiunas**

### CODE REVIEW

**Review by kabentley — CHANGES_REQUESTED** [review]
On thinking about this more, I think we should leave the "max-warnings 0" on. Allowing people to commit code with warnings is just a bad idea. They should look at them and disable them in their code if they aren't real problems. If you allow any warnings, then the list will grow and people will not see their newly generated ones.

But, making all our rules errors rather than warnings is fine,

**Comment by kabentley** [comment]
If we can always make all rules errors, then fine.

**Review by calebmshafer — APPROVED** [review]
LGTM.  I agree that warnings aren't really that useful because no one pays any attention to them, but I'd prefer we use eslint errors to handle it instead of "max-warnings" option.

Plus, this then pushes consumers of the package to the same best practices we're using in our repo.

**Comment by paulius-valiunas** [comment]
I've looked through our dependencies and there are no "warn" rules that aren't overwritten in our config. Exported ESLint configs normally don't change without a major version bump (it's considered a breaking change) so we should be safe.

**Review by pmconne — APPROVED** [review]

**Review by kabentley — APPROVED** [review]

**Review by saskliutas — APPROVED** [review]

**Review by bsteinbk — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Comment by paulius-valiunas** [comment]
@mgooding @wgoehrig could you please take a look at this? Thanks

**Pull request merged**
