### PR TITLE
More API promotions

### PR DESCRIPTION
**Pull request by pmconne**
Derived from reports of non-public API usage by SYNCHRO Field and the sample showcase.
Deferred for separate PR because they require API changes/cleanup: context reality models, spatial classification, planar clip masks.

### CODE REVIEW

**Comment by pmconne** [comment]
@NancyMcCallB @bsteinbk please advise how I address this:
```
==[ @bentley/ui-framework ]======================================[ 85 of 89 ]==
WARNING: 4 tests skipped in @bentley/ui-framework
npm ERR! Test failed.  See above for more details.
ERROR: Coverage for lines (99.96%) does not meet global threshold (100%)
ERROR: Coverage for functions (99.93%) does not meet global threshold (100%)
ERROR: Coverage for branches (99.96%) does not meet global threshold (100%)
ERROR: Coverage for statements (99.96%) does not meet global threshold (100%)
Returned error code: 1
"@bentley/ui-framework" failed to build.
```

**Comment by bsteinbk** [comment]
@pmconne - I will pull and see if I can reproduce. Typically this issue seems to be build machine specific. If you hit it again just drop the coverage to 99.9 and we will try to figure out separately.

**Comment by pmconne** [comment]
@bsteinbk see the tiny change I made to CategoryVisibilityHandler.tsx. I figure I just don't know the magic instanbul incantation to invoke.

**Comment by pmconne** [comment]
@bsteinbk coverage numbers repro'ed in CI build. I also now see 6 associated test failures. I replaced a `forEachOverride` function with `[Symbol.iterator]` and I don't fully understand how to make this `moq` thing understand that.
```
2021-05-25T12:27:08.7287220Z   1) CategoryVisibilityHandler
2021-05-25T12:27:08.7287710Z        changeVisibility
2021-05-25T12:27:08.7288420Z          calls enableSubcategoryCategory and enableCategory to ensure that parent category is enabled:
2021-05-25T12:27:08.7289210Z      TypeError: Result of the Symbol.iterator method is not an object
2021-05-25T12:27:08.7290450Z       at updateViewport (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:16:47)
2021-05-25T12:27:08.7291800Z       at Function.enableCategory (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:21:4)
2021-05-25T12:27:08.7293310Z       at Function.invoke (/Volumes/Builds/vsts_work_a/2/s/common/temp/node_modules/.pnpm/registry.npmjs.org/sinon/9.2.4/node_modules/sinon/lib/sinon/proxy-invoke.js:47:47)
2021-05-25T12:27:08.7294580Z       at Function.enableCategory (/Volumes/Builds/vsts_work_a/2/s/common/temp/node_modules/.pnpm/registry.npmjs.org/sinon/9.2.4/node_modules/sinon/lib/sinon/proxy.js:241:26)
2021-05-25T12:27:08.7296170Z       at CategoryVisibilityHandler.changeVisibility (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:10:51)
2021-05-25T12:27:08.7297680Z       at /Volumes/Builds/vsts_work_a/2/s/ui/framework/src/test/imodel-components/category-tree/CategoriesVisibilityHandler.test.ts:155:23
2021-05-25T12:27:08.7299210Z       at using (/Volumes/Builds/vsts_work_a/2/s/core/bentley/src/Disposable.ts:94:20)
2021-05-25T12:27:08.7300610Z       at Object.using (/Volumes/Builds/vsts_work_a/2/s/core/bentley/src/Disposable.ts:88:12)
2021-05-25T12:27:08.7302940Z       at Context.<anonymous> (src/test/imodel-components/category-tree/CategoriesVisibilityHandler.test.ts:154:13)
2021-05-25T12:27:08.7304210Z       at processImmediate (internal/timers.js:456:21)
2021-05-25T12:27:08.7304650Z 
2021-05-25T12:27:08.7305170Z   2) CategoryVisibilityHandler
2021-05-25T12:27:08.7305950Z        enableCategory
2021-05-25T12:27:08.7306540Z          enables category:
2021-05-25T12:27:08.7307130Z      TypeError: Result of the Symbol.iterator method is not an object
2021-05-25T12:27:08.7308480Z       at updateViewport (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:16:47)
2021-05-25T12:27:08.7310340Z       at Function.enableCategory (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:21:4)
2021-05-25T12:27:08.7312060Z       at Context.<anonymous> (src/test/imodel-components/category-tree/CategoriesVisibilityHandler.test.ts:313:33)
2021-05-25T12:27:08.7313420Z       at processImmediate (internal/timers.js:456:21)
2021-05-25T12:27:08.7313810Z 
2021-05-25T12:27:08.7314250Z   3) CategoryVisibilityHandler
2021-05-25T12:27:08.7314740Z        enableCategory
2021-05-25T12:27:08.7315220Z          disables category:
2021-05-25T12:27:08.7315790Z      TypeError: Result of the Symbol.iterator method is not an object
2021-05-25T12:27:08.7317020Z       at updateViewport (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:16:47)
2021-05-25T12:27:08.7318620Z       at Function.enableCategory (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:21:4)
2021-05-25T12:27:08.7319980Z       at Context.<anonymous> (src/test/imodel-components/category-tree/CategoriesVisibilityHandler.test.ts:318:33)
2021-05-25T12:27:08.7320770Z       at processImmediate (internal/timers.js:456:21)
2021-05-25T12:27:08.7321090Z 
2021-05-25T12:27:08.7321490Z   4) CategoryVisibilityHandler
2021-05-25T12:27:08.7321950Z        enableCategory
2021-05-25T12:27:08.7322460Z          disables category and subcategories:
2021-05-25T12:27:08.7323090Z      TypeError: Result of the Symbol.iterator method is not an object
2021-05-25T12:27:08.7324270Z       at updateViewport (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:16:47)
2021-05-25T12:27:08.7325600Z       at Function.enableCategory (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:21:4)
2021-05-25T12:27:08.7326940Z       at Context.<anonymous> (src/test/imodel-components/category-tree/CategoriesVisibilityHandler.test.ts:323:33)
2021-05-25T12:27:08.7327710Z       at processImmediate (internal/timers.js:456:21)
2021-05-25T12:27:08.7328030Z 
2021-05-25T12:27:08.7328440Z   5) CategoryVisibilityHandler
2021-05-25T12:27:08.7328910Z        enableCategory
2021-05-25T12:27:08.7329430Z          enables category in all viewports:
2021-05-25T12:27:08.7330050Z      TypeError: Result of the Symbol.iterator method is not an object
2021-05-25T12:27:08.7331240Z       at updateViewport (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:16:47)
2021-05-25T12:27:08.7332570Z       at Function.enableCategory (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:21:4)
2021-05-25T12:27:08.7333900Z       at Context.<anonymous> (src/test/imodel-components/category-tree/CategoriesVisibilityHandler.test.ts:352:33)
2021-05-25T12:27:08.7334670Z       at processImmediate (internal/timers.js:456:21)
2021-05-25T12:27:08.7335030Z 
2021-05-25T12:27:08.7335430Z   6) CategoryVisibilityHandler
2021-05-25T12:27:08.7335900Z        enableCategory
2021-05-25T12:27:08.7336410Z          disables category in all viewports:
2021-05-25T12:27:08.7337050Z      TypeError: Result of the Symbol.iterator method is not an object
2021-05-25T12:27:08.7339190Z       at updateViewport (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:16:47)
2021-05-25T12:27:08.7340950Z       at Function.enableCategory (src/ui-framework/imodel-components/category-tree/CategoryVisibilityHandler.tsx:21:4)
2021-05-25T12:27:08.7342400Z       at Context.<anonymous> (src/test/imodel-components/category-tree/CategoriesVisibilityHandler.test.ts:366:33)
```

**Comment by pmconne** [comment]
@bsteinbk @saskliutas I have all but 1 test passing now. Code coverage still < 100%. Please advise.
```
  1) CategoryVisibilityHandler
       enableCategory
         removes overrides per model when enabling category:
     TypeError: Cannot convert a Symbol value to a string
      at PropertyInfo.toString (D:\js\s\imodeljs\common\temp\node_modules\.pnpm\registry.npmjs.org\typemoq\2.1.0\node_modules\typemoq\dist\Proxy\Proxy\Proxy\Invocation.ts:245:31)
      at DynamicGetInvocation.ValueGetterInvocation.toString (D:\js\s\imodeljs\common\temp\node_modules\.pnpm\registry.npmjs.org\typemoq\2.1.0\node_modules\typemoq\dist\Proxy\Proxy\Proxy\Invocation.ts:96:21)
      at D:\js\s\imodeljs\common\temp\node_modules\.pnpm\registry.npmjs.org\typemoq\2.1.0\node_modules\typemoq\dist\InterceptorExecute.ts:72:63
      at Array.reduce (<anonymous>)
      at InterceptorExecute.throwVerifyCallCountException (D:\js\s\imodeljs\common\temp\node_modules\.pnpm\registry.npmjs.org\typemoq\2.1.0\node_modules\typemoq\dist\InterceptorExecute.ts:72:42)
      at InterceptorExecute.verifyCallCount (D:\js\s\imodeljs\common\temp\node_modules\.pnpm\registry.npmjs.org\typemoq\2.1.0\node_modules\typemoq\dist\InterceptorExecute.ts:64:18)
      at DynamicMock.verify (D:\js\s\imodeljs\common\temp\node_modules\.pnpm\registry.npmjs.org\typemoq\2.1.0\node_modules\typemoq\dist\DynamicMock.ts:44:31)
      at Context.<anonymous> (src\test\imodel-components\category-tree\CategoriesVisibilityHandler.test.ts:335:38)
      at processImmediate (internal/timers.js:461:21)
```

**Review by bbastings — APPROVED** [review]

**Comment by pmconne** [comment]
@bsteinbk correct. Approve PR please?

**Review by bsteinbk — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
