### PR TITLE
@bentley/imodeljs-native 2.10.3

### PR DESCRIPTION
**Pull request by calebmshafer**

### CODE REVIEW

**Comment by calebmshafer** [comment]
@pmconne not sure exactly what tests are failing but it looks like some in imodeljs-backend and core-full-stack tests are causing a crash.

**Comment by pmconne** [comment]
> @pmconne not sure exactly what tests are failing but it looks like some in imodeljs-backend and core-full-stack tests are causing a crash.

@kabentley did these tests all pass when you integrated your changes?
@calebmshafer The transaction manager fix targets GeoModeler, which has no released app and can easily obtain fix from a dev package - unclear that this should hold up 2.10 release.

**Review by grigasp — APPROVED** [review]

**Comment by pmconne** [comment]
@calebmshafer I pulled this branch and installed a locally-built add-on. `npm run test` in full-stack-tests/core and core/backend both succeed.

**Comment by pmconne** [comment]
`npm run cover` for core-full-stack-tests passed in chrome; abruptly terminated in electron with output below.
```
  Plan projections
    √ is obscured by background map based on settings (4305ms)

  Background map
    √ produces a different tile tree when background map settings change (7444ms)
    √ obscures model based on settings (2699ms)

  Blank Connection
    √ BlankConnection properties
    √ ScreenViewport with a BlankConnection

  CodeSpecs
    √ should load CodeSpecs

  Cached decorations
    √ should properly cache graphic decorations (4331ms)
    √ should properly cache canvas decorations (260ms)
    √ should properly cache html decorations (261ms)

  DevTools
    √ can fetch stats from backend (1064ms)
    - can ping backend
    √ can set log level
    √ Get the backend versions

  DisplayStyle
    √ should clone correctly
    √ should preserve sun direction
    √ should read sun direction from json
    √ Should override model appearance correctly
    √ should use iModel extents for thematic height range if unspecified
    √ should override selected settings

  ECSql Query
    √ Restart query (56ms)
    √ Paging Results (779ms)

  EmphasizeElements tests
    √ Emphasize add/replace/clear
    √ Isolate add/replace/clear
    √ Hide add/replace/clear
    √ Override add/replace/clear
    √ Applies correct overrides
    √ Override to/from key
    √ to/from JSON

  Events
    √ echo - roundtrip

  EventSource
    √ disposes EventSource when iModel is closed (596ms)
    √ can share RpcPushChannel
    √ disposes of global EventSource on shutdown (146ms)
    √ removes listeners upon disposal
    √ adds and removes listeners for individual events
    √ produces an inert channel for an empty name
    √ produces an inert channel if push events are not enabled
    √ does not accept listeners after disposal

  FeatureOverrideProvider
    √ should support deprecated getter and setter (169ms)
    √ adds and drops
    √ finds registered provider

  FeatureOverrides
    √ should create a uniform feature overrides object
    √ should create a non-uniform feature overrides object

  FeatureTable
    √ should pack and unpack

  FeatureSymbology.Overrides
    √ constructor with ViewState parameter works as expected
    √ isClassVisible works as expected
    √ isFeatureVisible works as expected
    √ getFeatureAppearance works as expected
    √ excludedElements works as expected
    √ model appearance overrides work as expected

  GeoCoord
    √ should get different results for different datums
    √ should read repeated requests from the cache
    √ should get some IModelCoords from the cache and calculate some
    √ should get some GeoCoords from the cache and calculate some

  GeometryAccumulator tests
    √ addPath works as expected
    √ addLoop works as expected
    √ addPolyface works as expected
    √ addGeometry works as expected
    √ clear works as expected
    √ toMeshBuilderMap works as expected
    √ toMeshes works as expected
    √ saveToGraphicList works as expected

  GraphicBuilder
    createTriMesh
      √ should create a simple mesh graphic
    createMesh
      √ should preserve polyface normals
      √ should generate normals for shapes if requested
      √ should not generate normals for 2d views

  InteractiveEditingSession
    √ should not be supported for read-only connections (317ms)
    √ should not be supported for iModels with BisCore < 1.0.11 (284ms)
    √ should not be supported for read-only iModels with BisCore >= 1.0.11 (292ms)
    √ should be supported for writable iModels with BisCore >= 1.0.11 (278ms)
    √ throws if begin is called repeatedly (307ms)
    √ throws if end is called repeatedly (281ms)
    √ throws if the iModel is closed before ending the session (324ms)
    √ dispatches events when sessions begin or end (269ms)

  Markup tests
    √ should initialize Markup
    √ viewing tools should fail when Markup active
    √ Markup Undo/Redo

  Mesh Builder Tests
    √ constructor
    √ addStrokePointLists
    √ addFromPolyface
    √ addFromPolyfaceVisitor
    √ createTriangleVertices
    √ createTriangle
    √ addPolyline
    √ addPointString
    √ addTriangle
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-full-stack-tests@ test:electron: `certa -r electron --grep "#integration" --invert "--cover"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core-full-stack-tests@ test:electron script.
```

**Comment by pmconne** [comment]
Closing - add-on requires fix for race condition resulting in access violation.

**Comment by calebmshafer** [comment]
> Closing - add-on requires fix for apparent race condition resulting in access violation.

@pmconne thanks, deleted this branch.  If this is not required for 2.10 release, maybe we just bring this into a 2.11.0-dev release later today?

Any objections to that or critical fixes we should wait for?  @grigasp @kabentley @khanaffan

**Comment by grigasp** [comment]
> > Closing - add-on requires fix for apparent race condition resulting in access violation.
> 
> @pmconne thanks, deleted this branch. If this is not required for 2.10 release, maybe we just bring this into a 2.11.0-dev release later today, or whenever @khanaffan has a fix for the access issue?
> 
> Any objections to that or critical fixes we should wait for? @grigasp @kabentley @khanaffan

I don't have anything planned for 2.10.

**Comment by kabentley** [comment]
I don't know of any issues and am not making additional addon changes

**Pull request closed without merging**
