### PR TITLE
bump xmldom to 0.6.0 to avoid bug where it keeps "<" in attributes

### PR DESCRIPTION
**Pull request by MichaelBelousov**
see https://github.com/xmldom/xmldom/pull/199 and https://github.com/xmldom/xmldom/issues/198
Some known schemas use `<` and `>` in display labels, so this was breaking the imodel transformer which used `xmldom@0.5.0`
to serialize schemas during export to be imported into the target iModel.

### CODE REVIEW

**Comment by MichaelBelousov** [comment]
going to add a test where a schema with `&` and `<` in a display label is run through the transformer

**Review by pmconne — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
@calebmshafer should this be backported?

**Review by calebmshafer — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
@calebmshafer I'm getting flaky integration and standalone backend  tests, could you take a look?

**Comment by calebmshafer** [comment]
@skirby1996 is working on the extract-api issue. There's some combination of node version and something else causing a bunch of people issues.

The `rush cover` failures for the backend are on my plate and haven't figured it out yet.

The flaky integration tests, I have not looked into those yet so not quite sure.

**Comment by MichaelBelousov** [comment]
@calebmshafer when we get past that stuff, can we also backport this fix to 2.19?

**Comment by MichaelBelousov** [comment]
@mergifyio update

**Comment by skirby1996** [comment]
@mergifyio backport release/2.19.x

**Pull request merged**
