### PR TITLE
Presentation: Fix presentation-test-app layout issue

### PR DESCRIPTION
**Pull request by grigasp**
After #1280, `GlobalContextMenu` started rendering a `<div />`, which broke presentation-test-app layout. This PR fixes it.

### CODE REVIEW

**Review by saskliutas — APPROVED** [review]

**Comment by roluk** [comment]
I think this needs to be fixed on the `GlobalContextMenu` component level by adding `display: "none"` style to that empty `div`. Otherwise, other applications will likely need to adapt their layout too.

**Comment by grigasp** [comment]
> I think this needs to be fixed on the `GlobalContextMenu` component level by adding `display: "none"` style to that empty `div`. Otherwise, other applications will likely need to adapt their layout too.

@bsteinbk what do you think?

**Comment by bsteinbk** [comment]
@grigasp What issue is this causing so I can add a test and fix the problem? I had to add that div so it can mount the div and I can extract the ownerDocument so context menus work in popout windows.

**Comment by bsteinbk** [comment]
@grigasp @roluk Can you used a PopupContextMenu like https://github.com/imodeljs/imodeljs/blob/bd45d29dcf184d8f071c6d9c8f52dcb450b1ff05/test-apps/ui-test-app/src/frontend/appui/frontstages/component-examples/SamplePopupContextMenu.tsx#L27 instead of a GlobalContextMenu? Like I said, I need to anchor the portal to a document in either the main window or a popup window. The target (to the button) in the PopupContextMenu gives me the ability to associate the popup with the proper window.

**Comment by grigasp** [comment]
> @grigasp @roluk Can you used a PopupContextMenu like
> 
> https://github.com/imodeljs/imodeljs/blob/bd45d29dcf184d8f071c6d9c8f52dcb450b1ff05/test-apps/ui-test-app/src/frontend/appui/frontstages/component-examples/SamplePopupContextMenu.tsx#L27
> 
> instead of a GlobalContextMenu? Like I said, I need to anchor the portal to a document in either the main window or a popup window. The target (to the button) in the PopupContextMenu gives me the ability to associate the popup with the proper window.

@bsteinbk We already have a good enough fix in this PR. I think what @roluk wants to say is that adding this div likely caused issues not only in our test app, but also other consumers, so it would make sense to fix it in `GlobalContextMenu`. I confirmed @roluk's suggestion helps for the layout issue in our test app. Can you check setting `display: "none"` still allows you to associate it with the window?

**Comment by bsteinbk** [comment]
@grigasp display: none works fine in popup windows, I will add that style to div to avoid problems.

**Comment by grigasp** [comment]
> @grigasp display: none works fine in popup windows, I will add that style to div to avoid problems.

Thanks. I'm abandoning this PR then.

**Pull request closed without merging**
