### PR TITLE
@bentley/imodeljs-native 2.11.3

### PR DESCRIPTION
**Pull request by pmconne**

### CODE REVIEW

**Comment by pmconne** [comment]
@evanpreslar-bentley one test is failing.
```
  ExtensionAdmin tests
    1) loads local extension
Error: iModel.js Shared Library @bentley/imodeljs-frontend is loaded, but is an incompatible version.
    at http://localhost:6010/imjs_extensions/loadingTestExtension/index.js:133:13
    at Object.<anonymous> (http://localhost:6010/imjs_extensions/loadingTestExtension/index.js:135:5)
    at __webpack_require__ (http://localhost:6010/webpack/bootstrap:19:1)
    at Object.<anonymous> (http://localhost:6010/src/common/extensions/loadingTestExtension/loadingTestExtension.ts:6:1)
    at __webpack_require__ (http://localhost:6010/webpack/bootstrap:19:1)
    at Object.<anonymous> (http://localhost:6010/imjs_extensions/loadingTestExtension/index.js:91:18)
    at __webpack_require__ (http://localhost:6010/webpack/bootstrap:19:1)
    at http://localhost:6010/webpack/bootstrap:83:1
    at http://localhost:6010/imjs_extensions/loadingTestExtension/index.js:87:10
```

**Comment by pmconne** [comment]
Closing in hopes that reopening will trigger a build...

**Review by grigasp — APPROVED** [review]
Approving presentation changes

**Review by bsteinbk — APPROVED** [review]

**Review by mgooding — APPROVED** [review]

**Comment by calebmshafer** [comment]
> @evanpreslar-bentley one test is failing.
> 
> ```
>   ExtensionAdmin tests
>     1) loads local extension
> Error: iModel.js Shared Library @bentley/imodeljs-frontend is loaded, but is an incompatible version.
>     at http://localhost:6010/imjs_extensions/loadingTestExtension/index.js:133:13
>     at Object.<anonymous> (http://localhost:6010/imjs_extensions/loadingTestExtension/index.js:135:5)
>     at __webpack_require__ (http://localhost:6010/webpack/bootstrap:19:1)
>     at Object.<anonymous> (http://localhost:6010/src/common/extensions/loadingTestExtension/loadingTestExtension.ts:6:1)
>     at __webpack_require__ (http://localhost:6010/webpack/bootstrap:19:1)
>     at Object.<anonymous> (http://localhost:6010/imjs_extensions/loadingTestExtension/index.js:91:18)
>     at __webpack_require__ (http://localhost:6010/webpack/bootstrap:19:1)
>     at http://localhost:6010/webpack/bootstrap:83:1
>     at http://localhost:6010/imjs_extensions/loadingTestExtension/index.js:87:10
> ```

Just to round out the discussion, we discussed the issue offline and @pmconne is side-stepping it for now by not doing a full rush update in this PR and only updating the pnpm-lock.yaml file for the new native package version.

Separately, we will be working on a more general fix to the way version comparison is handled for Extensions in a separate PR that will resolve this issue and a few others.  That fix should be ready before the 2.11.0 release.

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
