### PR TITLE
Customizable flash settings

### PR DESCRIPTION
**Pull request by pmconne**
As requested by @alarkbentley on behalf of an OpenCities Planner user, the flash behavior can now be customized for a Viewport.
The duration and maximum intensity can be configured. Lit geometry can also be forced to flash with the hilite color like unlit geometry does, instead of brightening.
`Viewport.setFlashed` used to take a duration specified by the caller, which was weird and was always hard-coded to 0.25 by each caller (there are only two). Now that duration is optional and ignored in favor of `FlashSettings.duration`.

### CODE REVIEW

**Comment by pmconne** [comment]
@markschlosseratbentley @bbastings please review.

**Review by markschlosseratbentley — APPROVED** [review]
I pulled + tested with the key-in, and all behaves as documented, from my experiments.  Looks great.

**Review by bbastings — APPROVED** [review]

**Comment by bbastings** [comment]
Just curious what settings OpenCities Planner will use...should we consider changing our default flash?

**Comment by pmconne** [comment]
> Just curious what settings OpenCities Planner will use...should we consider changing our default flash?

They want lit geometry to flash with the hilite color, like it would in an unlit view, but with a ratio < 1 so some of the element color is preserved.
I don't think we should change our default - using hilite color for flash doesn't work well when the element color is approximately the same as the hilite color.

**Pull request merged**
