### PR TITLE
Adding sectionToolGroupWithPanel definition in CoreTools

### PR DESCRIPTION
**Pull request by GintV**
Design Review and Synchro Viewer use identical sectionToolGroupWithPanel definition. Recently, a request was made for SYNCHRO Modeler to unify section tools group UI. I really hate copy-pasting code and having exact same definition in 3 different products, so I thought it would be best to have it in iModel.js. When products start using iModel.js version that has this definition in it, I will make effort to change their custom definitions in favor of CoreTools.sectionToolGroupWithPanel

### CODE REVIEW

**Review by bsteinbk — APPROVED** [review]

**Comment by bsteinbk** [comment]
@GintV  If you are having problems with test coverage issues not allowing the PR to merge, try the following. Add 
`CoreTools.sectionToolGroupWithPanel,`
below line 62 of CoreToolDefinitions.test.tsx.  Then delete CoreToolDefinitions.test.snap and run 
`npm run build && npm run cover` from ui\framework directory.  Finally commit the updated test and snap files.

**Comment by GintV** [comment]
@bsteinbk Well, I'm not sure if anything is failing or even ran, because all I see here is just
image

Also, I couldn't find any build related to this PR here as well:
https://dev.azure.com/bentleycs/iModelTechnologies/_build?definitionId=4300

**Comment by bsteinbk** [comment]
I don't use forked repos, but I have seen similar issues when others tried to merge from forks. Maybe @calebmshafer can provide guidance of merging from a fork. 
You will eventually see a failure as ui-framework requires 100% test coverage. So eventually you will need to add the changes I suggested.

**Pull request merged**
