### PR TITLE
Remove source target ellipsoid ids from transform v2

### PR DESCRIPTION
**Pull request by AlainRobertAtBentley**
Modified model to remove sourceEllipsoidId and targetEllipsoidId. These could be specified in the sourceEllipsoid and targetEllipsoid definitions provided. The previous model was copied from the previous Geodetic Datum model which made an indirect reference to an ellipsoid. In the case of a geodetic transform such indirection was unrequired an the sourceEllipsoid and targetEllipsoid contained the definition data required (polar and equatorial radiuses).
Note that since JSON def of transforms are not stored anywhere(yet) these changes do not not break any backward compatibility.

### CODE REVIEW

**Review by pmconne — CHANGES_REQUESTED** [review]
You need to run extract-api.

**Comment by AlainRobertAtBentley** [comment]
> You need to run extract-api.

Ran it. There are no API changes. This pull request only removes two members of an internal class

**Comment by AlainRobertAtBentley** [comment]
@pmconne Can we move this one forward. You requested I extract API but there was no API changes to commit. (API changes will be in the upcoming promotion to public of the whole thing)

**Review by pmconne — APPROVED** [review]
Thought I'd approved yesterday after you confirmed no API changes.

**Review by markschlosseratbentley — APPROVED** [review]

**Pull request merged**
