### PR TITLE
add utility to display-test-app to set a briefcase to be standalone for testing

### PR DESCRIPTION
**Pull request by kabentley**
should only be run with briefcase owner's permission.

### CODE REVIEW

**Comment by pmconne** [comment]
If we're going to do this, they're ought to be a giant warning somewhere.

I suspect if you try to do this to an iModel that's already standalone, but not marked as editable, it will throw.

Should this also apply to iModels opened from the file open dialog?

**Comment by kabentley** [comment]
> If we're going to do this, they're ought to be a giant warning somewhere.
I suppose it could work by making a copy. Whadyathink?

> I suspect if you try to do this to an iModel that's already standalone, but not marked as editable, it will throw.
nah, it will work fine. The check is in `IModelDb.ts` code this bypasses.

> Should this also apply to iModels opened from the file open dialog?
I'm not sure I understand the question. `BriefcaseConnection.openStandalone` will only open standalone files

**Comment by kabentley** [comment]
> EDIT: I see I misread - this is a _standalone_ utility, not part of display-test-app's startup.

Yes, i just snuck the source in display-test-app since that's where you need it.

**Review by pmconne — APPROVED** [review]

**Comment by kabentley** [comment]
i suppose it could have an argument to make the standalone editable. That would probably require yargs.

**Pull request merged**
