### PR TITLE
Allow target _blank in message boxes

### PR DESCRIPTION
**Pull request by kckst8**
DOMpurify removes all instances of target in anchor elements, even if proper relationships exist to keep it secure:

https://web.dev/external-anchors-use-rel-noopener/

This prevents adding links to message boxes that open in new windows, which is the desirable behavior in most instances.

I attempted to have this addressed in that library, but it appears it is recommended to work around it in consuming applications:

https://github.com/cure53/DOMPurify/issues/317#issuecomment-761088912

This change is workaround to allow the target attr if noopener or noreferrer rel also exist on the element

### CODE REVIEW

**Comment by DanEastBentley** [comment]
Please fix lint errors.

**Comment by kckst8** [comment]
> Please fix lint errors.

Fixed. As part of the fixes I disabled jam3/no-sanitizer-with-danger due to a false positive since I am calling the sanitizer function earlier with a condition.

**Review by DanEastBentley — APPROVED** [review]

**Comment by DanEastBentley** [comment]
Please address test coverage in ui-core

**Comment by kckst8** [comment]
> Please address test coverage in ui-core

on it

**Pull request merged**
