### PR TITLE
Update to Electron 11 to pick up Node fixes

### PR DESCRIPTION
**Pull request by calebmshafer**
The update to Electron 11 picks up a fix in Node (included in Node 12.18.3) for a crash during the destructor of ObjectWrap from napi. 

~~The Electron update looks to have fixed the issue @ramanujam-raman ran into during the Electron 10 update.  However, we need to do a bit more testing to make sure.  That's still a work in progress.~~ 

Update: This did not fix the issue with exiting the app on Windows in Certa.  Reverting those changes.  However, it still fixes the other issue so is worth updating.

tl;dr

While @wgoehrig and I were debugging into a MacOS hang in the CI builds, we discovered it is due to a crash in the core-full-stack-tests when running in Electron. After the initial crash, and the crash report pops up, a subsequent run of Electron opens a dialog that asks if you want to restart from the previous state.  This dialog is silly for a CI build since you don't want to usually use the previous state, we're working on fixing that in the CI infrastructure to avoid it hanging for that reason ever again.

After we figured that out, we started to dig into the crash itself.  From the callstack (let me know if you want the full callstack), we found it was due to the destructor of the ObjectWrap causing the issue,

```
1   com.github.Electron.framework 	0x000000010d763fde v8::internal::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*) + 862
2   com.github.Electron.framework 	0x000000010d8d2f5f v8::internal::HandleScope::Extend(v8::internal::Isolate*) + 399
3   com.github.Electron.framework 	0x000000010d7663b8 v8::HandleScope::CreateHandle(v8::internal::Isolate*, unsigned long) + 56
4   com.github.Electron.framework 	0x0000000112d09e51 napi_get_reference_value + 65
5   imodeljs.node                 	0x0000000121fb5c68 Napi::ObjectWrap<IModelJsNative::NativeDgnDb>::~ObjectWrap() + 48
...
```

The following trace of GitHub issues led us to find that this was an issue directly in Node and not napi.  The fix has been back ported to both >=12.18.3 and 14.x.  In order to pick this fix up in Electron, we have to update to Electron 11 which includes 12.18.3 as its Node version. 

- https://github.com/electron/electron/issues/25569
- https://github.com/nodejs/node-addon-api/issues/730
- https://github.com/nodejs/node-addon-api/pull/729
- https://github.com/nodejs/node/pull/33508

All of this said, we do have another crash in the native code from these tests which doesn't appear to be related.  It happens less often than the current one.  I'll follow up on that separately.

### CODE REVIEW

**Review by kabentley — APPROVED** [review]

**Review by scsewall — APPROVED** [review]

**Review by grigasp — APPROVED** [review]

**Review by paulius-valiunas — APPROVED** [review]

**Review by bsteinbk — APPROVED** [review]

**Comment by calebmshafer** [comment]
@pmconne @swwilson-bsi mind reviewing?

**Comment by pmconne** [comment]
@calebmshafer Before upgrading Node:
```
--[ FAILURE: @bentley/build-tools ]--------------------------[ 2.16 seconds ]--

../../common/temp/node_modules/.pnpm/registry.npmjs.org/tsutils/3.19.1_typescript@3.7.5/node_modules/tsutils/util/util.d.ts(256,65): error TS1110: Type expected.
```
After upgrading to Node 14.15.4:
```
[j2 10:47:43.88] d:\j2\s\imodeljs>rush build --to display-test-app
Your version of Node.js (14.15.4) has not been tested with this release of Rush. Please consider installing a newer version of the "@microsoft/rush" package, or downgrading Node.js.

Rush version 5.34.2 is not currently installed. Installing...
Trying to acquire lock for rush-5.34.2
Deleting old files from C:\Users\paul.connelly\.rush\node-v14.15.4\rush-5.34.2
Copying d:\j2\s\imodeljs\common\config\rush\.npmrc --> C:\Users\paul.connelly\.rush\node-v14.15.4\rush-5.34.2\.npmrc

Running "npm install" in C:\Users\paul.connelly\.rush\node-v14.15.4\rush-5.34.2
Successfully installed Rush version 5.34.2 in C:\Users\paul.connelly\.rush\node-v14.15.4\rush-5.34.2.

Rush Multi-Project Build Tool 5.34.2 - https://rushjs.io
Node.js version is 14.15.4 (LTS)



ERROR: Your dev environment is running Node.js version v14.15.4 which does not meet the requirements for building this repository.  (The rush.json configuration requires
nodeSupportedVersionRange=">=10.17.0 <13.0.0")

[j2 10:52:11.84] d:\j2\s\imodeljs>rush clean
Your version of Node.js (14.15.4) has not been tested with this release of Rush. Please consider installing a newer version of the "@microsoft/rush" package, or downgrading Node.js.


Rush Multi-Project Build Tool 5.34.2 - https://rushjs.io
Node.js version is 14.15.4 (LTS)



ERROR: Your dev environment is running Node.js version v14.15.4 which does not meet the requirements for building this repository.  (The rush.json configuration requires
nodeSupportedVersionRange=">=10.17.0 <13.0.0")

[j2 10:52:17.50] d:\j2\s\imodeljs>rush build --to display-test-app
[j2 10:52:20.05] d:\j2\s\imodeljs>
[j2 10:53:44.87] d:\j2\s\imodeljs>rush install
Your version of Node.js (14.15.4) has not been tested with this release of Rush. Please consider installing a newer version of the "@microsoft/rush" package, or downgrading Node.js.


Rush Multi-Project Build Tool 5.34.2 - https://rushjs.io
Node.js version is 14.15.4 (LTS)



ERROR: Your dev environment is running Node.js version v14.15.4 which does not meet the requirements for building this repository.  (The rush.json configuration requires
nodeSupportedVersionRange=">=10.17.0 <13.0.0")
```

**Comment by calebmshafer** [comment]
@pmconne yes, this doesn't yet support Node 14.x.  That will be a separate PR.

Fixing the tsutils issue now.  I'll push an update in a minute.

**Review by pmconne — APPROVED** [review]
I couldn't find any regressions in display-test-app. OIDC sign-in still works.

**Review by ramanujam-raman — APPROVED** [review]

**Review by wgoehrig — APPROVED** [review]

**Pull request merged**
