### PR TITLE
Preceding checkpointv2 relationship fix

### PR DESCRIPTION
**Pull request by austeja-bentley**
-> Changed the CheckpointV2Handler to use the newly implemented relationship for preceding checkpoint query
-> API break: changed the CheckpointV2Query.precedingCheckpoint method name to CheckpointV2Query.precedingCheckpointV2 to match the relationship

### CODE REVIEW

**Comment by wgoehrig** [comment]
@nick4598 @paulius-valiunas we'll need to update the v2 checkpoint agent once this merges.

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
