### PR TITLE
Promote GCS model to @public

### PR DESCRIPTION
**Pull request by AlainRobertAtBentley**
Promoted the Geographic Coordinate Reference System model to public.

### CODE REVIEW

**Review by pmconne — CHANGES_REQUESTED** [review]
You definitely need to run extract-api this time, right?

**Comment by AlainRobertAtBentley** [comment]
@pmconne I ran rush extract-api but the result changes apparently were only the CR/LF only. I do not understand where I missed something in the extract api process.

**Comment by AlainRobertAtBentley** [comment]
@pmconne Tried again after the rush change but no changes extracted by rush extract-api. Would I need to add the source files to some list for them to be taken into account in the API extraction process?

**Comment by pmconne** [comment]
@AlainRobertAtBentley the problem appears to be that your files were never added to imodeljs-common.ts - the barrel file from which all APIs are exported. Therefore no one can import your types from outside this package, and extract-api doesn't see them either.

**Comment by AlainRobertAtBentley** [comment]
@pmconne I have added the entries in imodeljs-common.ts and have added tags 
/** @packageDocumentation
 * @module Geometry
 */
 In each file but still rush extract-api did not modify anything. There must be something else.

**Comment by pmconne** [comment]
@AlainRobertAtBentley 
```
cd core/common
npm run clean
npm run build
npm run extract-api
```

You always have to rebuild before extract-api or lint.

**Comment by AlainRobertAtBentley** [comment]
@pmconne I think I got it this time!

**Review by pmconne — CHANGES_REQUESTED** [review]
Looks good. `@public` properties/methods/types should all be documented though. A brief description may suffice.

**Comment by AlainRobertAtBentley** [comment]
@pmconne I think I got all undocumented properties. I reviewed but could have missed one.

**Comment by pmconne** [comment]
@AlainRobertAtBentley the files generated by extract-api tell you which are undocumented - you got them all.

**Review by pmconne — APPROVED** [review]

**Comment by public** [comment]
> * Promote GCS model to @public

Mission accomplished 👍

**Pull request merged**
