### PR TITLE
Option to generate edges for decorations

### PR DESCRIPTION
**Pull request by pmconne**
More or less a straight port of native MeshEdgesBuilder, sans (for now?) polyline edge chains.
GraphicBuilderOptions can specify whether to generate edges for surfaces. Defaults to false unless GraphicType.Scene in which case it generates edges if viewport's view flags require them.
Unless otherwise specified, normals are always generated if edges are generated, because they are used to compute the depth tolerance to combat z-fighting.
Added another example to display-test-app that just produces a bunch of different types of geometry as decorations, for testing. You can play with the render mode, edge settings, etc - they affect the decorations as if they were part of the scene.
Also added GraphicBuilder.addSolidPrimitive - surprisingly, this was never implemented.
Fixed issue wherein a pickable decoration placed inside a graphic branch would not be considered pickable (would not draw for readPixels()).
Made analysis style example produce edges for the analysis meshes. Need to build normals for them to fix z-fighting (in subsequent PR).

Incidental changes:
- Add equivalents of Map.values and Map.keys to Dictionary.
- Add Dictionary.findOrInsert.
- PolyfaceData.getPoint accepts an optional output parameter.
- Move a bunch of tests for frontend code from core-full-stack-tests to imodeljs-frontend.

TODO:
- ~~Fix edges z-fighting with their surfaces when animated by an analysis style.~~ Address in separate PR - need normals - specific to polyfaces.
- ~~Polyline edge chains?~~ Not now.

### CODE REVIEW

**Comment by pmconne** [comment]
@RBBentley Do you recall if you fixed the ugly animated edges before or after the port to TypeScript? Or, do you recall what caused the problem?

**Comment by RBBentley** [comment]
I think I fixed in typescript -- I'll try to find fix.

**Comment by pmconne** [comment]
> I think I fixed in typescript -- I'll try to find fix. The cantilever beam GIF in the documentation looks fine - So must have been in typescript. Do you still have the snapshot created from the example?

The problem is the lack of normals. We don't do the surface discard check if no normals; and we need the normal for that check because we compute the depth tolerance based on angle of triangle to screen.

I'll port PolyfaceHeader::BuildNormalsFast() so we can generate normals for these polyfaces. (We should already be generating proper normals for other types of geometry).

**Comment by pmconne** [comment]
@Mergifyio update

**Review by RBBentley — APPROVED** [review]
Excellent -- moving this functionality is very worthwhile.

**Review by markschlosseratbentley — APPROVED** [review]

**Review by kabentley — APPROVED** [review]

**Pull request merged**
