### PR TITLE
UI: Update VirtualizedPropertyGrid element spacing

### PR DESCRIPTION
**Pull request by roluk**
Some more adjustments to element positioning in VirtualizedPropertyGrid after migrating to @itwinui-react components. Notable changes: 

* Adds padding around the whole property grid to match previous look
* Simplifies some CSS rules
* Increases information density in vertical mode

Known issues:
* Expandable block chevrons are misaligned
* There is no top padding in expandable block content
* Editors cause properties to nudge slightly

### CODE REVIEW

**Review by grigasp — CHANGES_REQUESTED** [review]
Collapsed categories loose top, left and right borders:
image

**Comment by grigasp** [comment]
I looked at the chevron spacing problem... I think the issue is that line height of the title is too large, which makes the whole expandable block header `2px` larger than needed for the chevron, thus offsetting it by `1px`.

`.iui-header` takes its height from its content (see disabled attribute): 
image

The content area height is 22px and it comes from `line-height` of `.iui-title`: 
image

And the chevron expects the height to be `20px` (`12px` content + `4px` top margin + `4px` bottom margin): 
image

All size-related styles come from `small-itwinui-expandable-block` mixin, so I believe that's where the fix should be made. @DanEastBentley, @bsteinbk what do you think?

**Comment by bsteinbk** [comment]
@NancyMcCallB  @grigasp I agree that the chevron alignment should be fixed in the `small-itwinui-expandable-block` mixin, I can see even it not working in our example components page.  @DanEastBentley will be back next week and he is currently best suited to fix the issue, can it wait until then.

**Comment by grigasp** [comment]
> @NancyMcCallB @grigasp I agree that the chevron alignment should be fixed in the `small-itwinui-expandable-block` mixin, I can see even it not working in our example components page. @DanEastBentley will be back next week and he is currently best suited to fix the issue, can it wait until then.

Yes, I think it can wait.

**Comment by roluk** [comment]
> 
> 
> Collapsed categories loose top, left and right borders:
> image

This behavior is defined in `@itwin/itwinui-react` package.

**Comment by grigasp** [comment]
> > Collapsed categories loose top, left and right borders:
> > image
> 
> This behavior is defined in `@itwin/itwinui-react` package.

Ok, approving the PR. @DanEastBentley, please have a look at this when you get a chance.

**Review by grigasp — APPROVED** [review]

**Pull request merged**
