### PR TITLE
xmldom dependency in ecschema-metadata should be a real dependency, not devDep

### PR DESCRIPTION
**Pull request by MichaelBelousov**
- it is being used at runtime in `Schema.ts` and therefore must be a real production dependency, not a devDependency
- as it is now, it breaks devDependency-pruned builds of electron desktop apps that transitively depend on this, the workaround for now is to explicitly depend on xmldom in those apps until this is fixed
- to prevent this in the future, can we use something like [this eslint rule](https://github.com/lennym/eslint-plugin-implicit-dependencies#eslint-plugin-implicit-dependencies)? If we have an approval process for non-standard eslint rules we can go through, I can add such a rule to this PR after it is approved

### CODE REVIEW

**Comment by calebmshafer** [comment]
@MichaelBelousov this was a devDependency because when you're on the frontend you technically do not need an this implementation. It is only needed when running, and using, ecschema-metadata on the backend.  Maybe at that point it should really be an `optionalDependency` but I don't agree that it should always be included as a real dep.

**Comment by MichaelBelousov** [comment]
@mergifyio update

**Comment by MichaelBelousov** [comment]
@calebmshafer can you make a final call on this? Should we make xmldom an optional dependency and throw an error when using `Schema.toXmlString` on "optional dependency not satisfied" when it isn't installed?

**Comment by calebmshafer** [comment]
I'd be in favor of doing that instead of requiring the xmldom dependency. I must have missed the initial PR that added the Schema.toXmlString method, could have saved you the headache...

**Comment by MichaelBelousov** [comment]
> I'd be in favor of doing that instead of requiring the xmldom dependency. I must have missed the initial PR that added the Schema.toXmlString method, could have saved you the headache...

not a problem, I'll add that

**Comment by MichaelBelousov** [comment]
@calebmshafer, not sure if you wanted to avoid this, but because the imodel transformer in imodeljs-backend uses this feature, I had to add a dependency on xmldom to the backend package. We could add it as an optional dependency to the backend package, and put a note in the transformer documentation that consumers will need to install xmldom to use the imodel transformer. It would be nicer if imodel-transformer were its own package of course, but I don't believe we can split that out right now.

**Comment by MichaelBelousov** [comment]
I need to at least change this to use browser APIs where available, but considering maybe removing `toXmlString` right now entirely and have the transformer which requires it on the backend serialize the xml document it gets from `toXml` itself

**Comment by calebmshafer** [comment]
@MichaelBelousov that sounds like a better alternative to me rather than complicating what ecschema-metadata is doing with it.  Then it'd be more isolated.

Also, I forget what PR comment it was in but for one of them you mentioned it'd be easier if iModelTransformer was out of the backend package.  I completely agree and meant to chat with you about that at some point. With us working on 3.0, I feel like that's the time to make the split if we're going to.  Any objections or hesitation with doing it?

**Comment by MichaelBelousov** [comment]
> Also, I forget what PR comment it was in but for one of them you mentioned it'd be easier if iModelTransformer was out of the backend package. I completely agree and meant to chat with you about that at some point. With us working on 3.0, I feel like that's the time to make the split if we're going to. Any objections or hesitation with doing it?

No, let me know if you need help or want to give that task to me.

**Comment by calebmshafer** [comment]
@MichaelBelousov if you could pick that up that'd be great. Thanks!

**Comment by MichaelBelousov** [comment]
I'm going to change this PR to just remove `toSchemaXml`, but it will be dependent on #2023 which removes the dependency in imodel-transformer

**Comment by MichaelBelousov** [comment]
the removal of `toSchemaXml` is here https://github.com/imodeljs/imodeljs/pull/2092

**Pull request closed without merging**
