### PR TITLE
fix imports from CheckpointConnection to not reference own barrel

### PR DESCRIPTION
**Pull request by jason-crow**

### CODE REVIEW

**Review by pmconne — COMMENTED** [review]
What was wrong with the previous PR?

**Review by kabentley — APPROVED** [review]

**Review by aruniverse — APPROVED** [review]

**Comment by aruniverse** [comment]
> What was wrong with the previous PR?

nothing code wise, issue with the cla bot

**Comment by calebmshafer** [comment]
@jason-crow I think you have your local git setup with a different noreply email than what's associated with the `jason-crow`  account.  That may be causing these issues. Can you check https://github.com/settings/emails to see what the noreply email is?

**Comment by jason-crow** [comment]
@mergifyio backport release/2.14.x

**Comment by jason-crow** [comment]
@mergifyio backport release/2.15.x

**Comment by jason-crow** [comment]
OK should be good now, thanks @calebmshafer for your help!

**Pull request merged**
