### PR TITLE
Make BeEvent.raiseEvent type safe

### PR DESCRIPTION
**Pull request by kabentley**
fix places where we're raising events with the wrong arguments

### CODE REVIEW

**Review by scsewall — COMMENTED** [review]
Looks like there might be minor API changes. Do you need to run extract-api?

**Comment by kabentley** [comment]
@grigasp The signature of this call is not right, but I can't tell how to fix it. Can you please help?

https://github.com/imodeljs/imodeljs/blob/1d9d124eab57af0f0c843232a86597b4a231d5d6/presentation/frontend/src/presentation-frontend/RulesetVariablesManager.ts#L153

**Comment by kabentley** [comment]
> Looks like there might be minor API changes. Do you need to run extract-api?

yes, I will. But I haven't gotten it to build successfully yet.

**Comment by grigasp** [comment]
`rush build` succeeds now

**Review by grigasp — APPROVED** [review]

**Review by pmconne — APPROVED** [review]

**Comment by kabentley** [comment]
@pmconne this now doesn't compile:

https://github.com/imodeljs/imodeljs/blob/1c8a2435c717dabc512062db644026d7a57be323/core/frontend/src/ViewState.ts#L1026

Should it allow `undefined`?

**Comment by pmconne** [comment]
> Should it allow `undefined`?

Yes. Great to have compiler catching these bugs now.

**Pull request merged**
