### PR TITLE
remove deprecated functions from transformer package api

### PR DESCRIPTION
**Pull request by MichaelBelousov**
- remove deprecated functions from transformer package api, and remove their references
  - one doc reference was moved to the replacement method name
  - one test reference that no longer needed to test the deprecated method

### CODE REVIEW

**Review by pmconne — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
@Mergifyio update

**Comment by MichaelBelousov** [comment]
@ColinKerr can you review this? also do you know if github always requires a non-authoring code owner's review when you have multiple code owners?

**Comment by calebmshafer** [comment]
@MichaelBelousov yes it will require the non-author's review so if you're making changes and @ColinKerr is the only other reviewer, he will have to review it.

**Review by ColinKerr — APPROVED** [review]

**Comment by MichaelBelousov** [comment]
@mergifyio update

**Pull request merged**
