### PR TITLE
Fixed scrolling in Table component

### PR DESCRIPTION
**Pull request by DanEastBentley**

### CODE REVIEW

**Review by bsteinbk — APPROVED** [review]

**Comment by DanEastBentley** [comment]
@mergifyio backport release/2.19.x

**Comment by DanEastBentley** [comment]
@mergifyio backport release/2.18.x

**Comment by DanEastBentley** [comment]
@mergifyio backport release/2.17.x

**Comment by DanEastBentley** [comment]
@mergifyio backport release/2.16.x

**Pull request merged**
