### PR TITLE
Checkpoints v2 client

### PR DESCRIPTION
**Pull request by amikoliunas**

### CODE REVIEW

**Review by calebmshafer — CHANGES_REQUESTED** [review]
Looks like the build is failing due to a lint issue and then an issue with the linux build. I'll work on trying to figure out what's wrong with the linux one.

Can you take a look a the lint error?  

```
D:\a\1\s\core\backend\src\test\standalone\IModel.test.ts(1738,7): error object-shorthand : Expected property shorthand.
```

**Comment by amikoliunas** [comment]
> Looks like the build is failing due to a lint issue and then an issue with the linux build. I'll work on trying to figure out what's wrong with the linux one.
> 
> Can you take a look a the lint error?
> 
> ```
> D:\a\1\s\core\backend\src\test\standalone\IModel.test.ts(1738,7): error object-shorthand : Expected property shorthand.
> ```

Sure, fixed

**Review by calebmshafer — APPROVED** [review]

**Review by calebmshafer — CHANGES_REQUESTED** [review]
Hold this until iModelHub is updated to accept this.

**Review by calebmshafer — APPROVED** [review]

**Comment by calebmshafer** [comment]
The hosted build is still broken due to an issue with Certa on Linux (@wgoehrig and I will dig into that more).  However, I ran this on our internal CI infrastructure and everything seems to be good to go.

If you have access to them, here are builds,

Docs: https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=649918&view=results
Build: https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=650455&view=results
Integration: https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=650457&view=results

**Comment by calebmshafer** [comment]
@Mergify backport release/2.10.0

**Pull request merged**
