### PR TITLE
Version compare: property checksums

### PR DESCRIPTION
**Pull request by diegopinate**
Handle property checksums generated in new addon code

### CODE REVIEW

**Review by pmconne — CHANGES_REQUESTED** [review]
You did not follow [these instructions](https://dev.azure.com/bentleycs/iModelTechnologies/_wiki/wikis/iModelTechnologies.wiki/8690/iModel.js-Node-add-on-development). You need to run extract-api, `rush change`, lint, tests, etc.

**Comment by diegopinate** [comment]
yes, forgot to rush change. done.

**Comment by pmconne** [comment]
> yes, forgot to rush change. done.

You added a new exported interface `ProcessChangesetOptions` that is lacking a release tag. extract-api should have complained about missing release tag and, after you added one, should have produced changes in /common/api/.
Please follow **all** of the steps in that article. If you don't, you break the addon build.

**Comment by diegopinate** [comment]
> > yes, forgot to rush change. done.
> 
> You added a new exported interface `ProcessChangesetOptions` that is lacking a release tag. extract-api should have complained about missing release tag and, after you added one, should have produced changes in /common/api/.
> Please follow **all** of the steps in that article. If you don't, you break the addon build.

I have pushed the release tag, linter fixes and extract-api.

**Review by pmconne — APPROVED** [review]

**Pull request merged**
