### PR TITLE
Update UiSettings in ui-core to correct release tag

### PR DESCRIPTION
**Pull request by calebmshafer**
Update UiSettings in ui-core to `public` to better align with the usage in ui-framework.

Downgrade the `ToolAssistanceFieldProps.uiSettings` to internal until docs issue is fixed.

### CODE REVIEW

**Comment by kabentley** [comment]
@calebmshafer why don't the build jobs run? What does "Expected — Waiting for status to be reported" mean?

**Comment by calebmshafer** [comment]
> /azp run

@kabentley they don't run by default for Draft PRs. Right now, `/azp run` doesn't queue the regular builds either, it starts the public build instead.

**Pull request merged**
