### PR TITLE
Fix BentleyMochaReporter to ban `.only` in PR builds again

### PR DESCRIPTION
**Pull request by wgoehrig**
Updating mocha to 8.3.2 (#1190) broke our mechanism for failing builds when someone pushes a commit that uses `.only` in a test.

I could probably come up with a cleaner implementation for this by moving it out of our reporter file entirely and configuring all tests to require another file, but keeping this in the reporter is awfully convenient given the multitude of test configurations we have today...

### CODE REVIEW

**Review by calebmshafer — APPROVED** [review]
I agree, I started looking into this as well and I don't really think we need/should have our own custom reporter anymore.

The 2 main things it does are forbidOnly and reporting the number of skipped tests.  The number of skipped tests is fairly useless since most of the skipped ones are due to the greps we use...

It does handle reporting out to stderr but I feel like that should be a mocha feature as well and not something we need to do...

**Comment by calebmshafer** [comment]
@Mergifyio backport release/2.17.x

**Comment by wgoehrig** [comment]
> The 2 main things it does are forbidOnly and reporting the number of skipped tests. The number of skipped tests is fairly useless since most of the skipped ones are due to the greps we use...

@calebmshafer That's not exactly true - the main reason we made a custom reporter in the first place was to use _both_ the spec (console output) _and_ JUnit XML reporters in CI builds.  Everyone today relies on the spec output when debugging failures, but the XML results are crucial to gathering long-term data on test failure trends/identifying flaky tests.

**Comment by calebmshafer** [comment]
> > The 2 main things it does are forbidOnly and reporting the number of skipped tests. The number of skipped tests is fairly useless since most of the skipped ones are due to the greps we use...
> 
> @calebmshafer That's not exactly true - the main reason we made a custom reporter in the first place was to use _both_ the spec (console output) _and_ JUnit XML reporters in CI builds. Everyone today relies on the spec output when debugging failures, but the XML results are crucial to gathering long-term data on test failure trends/identifying flaky tests.

@wgoehrig yes but if we do have a separate config for CI then we can just specify the additional reporter than, right? Or I guess we could separate our reporter out into it's own package rather than having it half live in build-tools.

**Comment by wgoehrig** [comment]
> but if we do have a separate config for CI then we can just specify the additional reporter than, right?
No, mocha doesn't support multiple reporters (at least AFAIK).

> Or I guess we could separate our reporter out into it's own package rather than having it half live in build-tools.
That's not a bad idea, but I just figured it wasn't worth the overhead of maintaining/publishing yet another package (everyone using it is already consuming build-tools).

**Pull request merged**
