### PR TITLE
Rename packages to use @itwin scope

### PR DESCRIPTION
**Pull request by skirby1996**
Rename a number of packages in the repo to use the @itwin scope instead of the @bentley scope. The full list of package changes are as follows (as well as in NextVersion.md).

| Current                                | New                                  |
|----------------------------------------|--------------------------------------|
| @bentley/imodeljs-backend              | @itwin/core-backend                  |
| @bentley/imodeljs-common               | @itwin/core-common                   |
| @bentley/imodeljs-frontend             | @itwin/core-frontend                 |
| @bentley/geometry-core                 | @itwin/core-geometry                 |
| @bentley/ecschema-metadata             | @itwin/ecschema-metadata             |
| @bentley/ecschema-locaters             | @itwin/ecschema-locaters             |
| @bentley/ecschema-editing              | @itwin/ecschema-editing              |
| @bentley/bentleyjs-core                | @itwin/core-bentley                  |
| @bentley/orbitgt-core                  | @itwin/core-orbitgt                  |
| @bentley/frontend-devtools             | @itwin/frontend-devtools             |
| @bentley/webgl-compatibility           | @itwin/webgl-compatibility           |
| @bentley/imodeljs-transformer          | @itwin/core-transformer              |
| @bentley/imodeljs-markup               | @itwin/core-markup                   |
| @bentley/imodeljs-editor-common        | @itwin/editor-common                 |
| @bentley/imodeljs-editor-backend       | @itwin/editor-backend                |
| @bentley/imodeljs-editor-frontend      | @itwin/editor-frontend               |
| @bentley/analytical-backend            | @itwin/analytical-backend            |
| @bentley/linear-referencing-backend    | @itwin/linear-referencing-backend    |
| @bentley/linear-referencing-common     | @itwin/linear-referencing-common     |
| @bentley/physical-material-backend     | @itwin/physical-material-backend     |
| @bentley/presentation-backend          | @itwin/presentation-backend          |
| @bentley/presentation-common           | @itwin/presentation-common           |
| @bentley/presentation-frontend         | @itwin/presentation-frontend         |
| @bentley/presentation-components       | @itwin/presentation-components       |
| @bentley/presentation-testing          | @itwin/presentation-testing          |
| @bentley/ui-abstract                   | @itwin/appui-abstract                |
| @bentley/ui-components                 | @itwin/components-react              |
| @bentley/ui-core                       | @itwin/core-react                    |
| @bentley/ui-imodel-components          | @itwin/imodel-components-react       |
| @bentley/ui-ninezone                   | @itwin/appui-layout-react            |
| @bentley/ui-framework                  | @itwin/appui-react                   |
| @bentley/ecschema2ts                   | @itwin/ecschema2ts                   |
| @bentley/webpack-tools-core            | @itwin/core-webpack-tools            |
| @bentley/backend-webpack-tools         | @itwin/backend-webpack-tools         |
| @bentley/build-tools                   | @itwin/build-tools                   |
| @bentley/eslint-plugin                 | @itwin/eslint-plugin                 |
| @bentley/imodeljs-quantity             | @itwin/core-quantity                 |
| @bentley/imodeljs-i18n                 | @itwin/core-i18n                     |
| @bentley/hypermodeling-frontend        | @itwin/hypermodeling-frontend        |
| @bentley/electron-manager              | @itwin/electron-manager              |
| @bentley/mobile-manager                | @itwin/mobile-manager                |
| @bentley/express-server                | @itwin/express-server                |
| @bentley/ecschema-rpcinterface-common  | @itwin/ecschema-rpcinterface-common  |
| @bentley/ecschema-rpcinterface-impl    | @itwin/ecschema-rpcinterface-impl    |
| @bentley/ecschema-rpcinterface-tests   | @itwin/ecschema-rpcinterface-tests   |
| @bentley/certa                         | @itwin/certa                         |
| @bentley/perf-tools                    | @itwin/perf-tools                    |
| @bentley/oidc-signin-tool              | @itwin/oidc-signin-tool              |
| @bentley/geonames-extension            | @itwin/geonames-extension            |
| @bentley/map-layers                    | @itwin/map-layers                    |
| @bentley/rpcinterface-full-stack-tests | @itwin/rpcinterface-full-stack-tests |
| @bentley/imodelhub-client-tests        | @itwin/imodelhub-client-tests        |

### CODE REVIEW

**Review by pmconne — APPROVED** [review]
Uh I'm just going to assume if it builds it's ok. 4633 files is a bit much.

**Comment by pmconne** [comment]
FYI NextVersion.md contains many references to the old package names.

**Review by NancyMcCallB — COMMENTED** [review]
I thought we were going to drop the ui- from the beginning of the package names becauwse we added react to the end?

**Comment by skirby1996** [comment]
> FYI NextVersion.md contains many references to the old package names.

Thanks for the heads up, should be fixed now.

**Comment by skirby1996** [comment]
@mergifyio update

**Comment by aruniverse** [comment]
Don't need to update codeowners?

**Comment by calebmshafer** [comment]
@skirby1996 looks like we're missing Certa and build-tools in the list. Mind updating those to be iTwin scoped?

**Comment by aruniverse** [comment]
> @skirby1996 looks like we're missing Certa and build-tools in the list. Mind updating those to be iTwin scoped?

Theres a bunch of bentley scoped pkgs in rush.json that also probably need to get updated, ie hypermodeling, electron, mobile, rpc, etc

**Comment by skirby1996** [comment]
Okay, I was going off that list of packages we set up but I can go ahead and move the rest of the packages over to the itwin scope  as well.

**Review by grigasp — APPROVED** [review]

**Comment by NancyMcCallB** [comment]
Hey, can we remove the "ui-" from the front of the package names ending in "-react"?

**Comment by skirby1996** [comment]
@NancyMcCallB We missed a few other packages so I'm in the process of updating those as well as fixing the ui package names, should have that updated soon.

**Comment by kckst8** [comment]
I have some concerns about these proposed names:

image

We already have:

@itwin/viewer-components-react
@itwin/admin-components-react

and now we are adding:

@itwin/imodel-components-react
@itwin/components-react

As a user, I would have no idea what is in each of these packages or how they differentiate at all. Perhaps we should become more specific or, better yet, combine related items into fewer generic component packages?

**Review by NancyMcCallB — APPROVED** [review]

**Review by kabentley — APPROVED** [review]

**Pull request merged**
