### PR TITLE
Update to latest react-dnd version

### PR DESCRIPTION
**Pull request by GerardasB**
This PR includes following changes:
- Update to latest `react-dnd` version (from **5.x** to **11.x**). Mainly to fix reported `npm audit` [issue](https://www.npmjs.com/advisories/1556).
- Deprecate poorly supported drag and drop types and components (in preparation to remove exposed `react-dnd` types in `ui-components` API).
- Remove `react-dnd-test-backend` in favor of `react-dnd-test-utils`

### CODE REVIEW

**Review by grigasp — APPROVED** [review]

**Review by pmconne — COMMENTED** [review]
I see a bunch of new `@deprecated` tags - do you expect callers to exist who might need to know what they should use instead?

**Comment by GerardasB** [comment]
> I see a bunch of new `@deprecated` tags - do you expect callers to exist who might need to know what they should use instead?

@pmconne That's a good catch, but I've left these deprecated tags w/o migration strategy because that doesn't exist at the moment.
We expect that these deprecated (mostly experimental - marked as **beta**) API's are rarely used by our consumers and it would be more useful to get rid of this functionality (instead of maintaining support, which is troublesome due to re-exposed types of 3rd party package in our API).
Of course, we will have to revisit this if we'll receive any _actual_ inquiries about these deprecations.

**Review by pmconne — APPROVED** [review]

**Review by bsteinbk — APPROVED** [review]

**Pull request merged**
