### PR TITLE
Precompile shaders by default

### PR DESCRIPTION
**Pull request by markschlosseratbentley**
This PR enables the 'doIdleWork' property on RenderSystem.Options by default, which allows the WebGL renderer to precompile shaders before any Viewport is opened.
See NextVersion.md for details on this change.

### CODE REVIEW

**Review by pmconne — APPROVED** [review]
Did you follow up with @jason-crow at all?

**Comment by markschlosseratbentley** [comment]
@pmconne 
> Did you follow up with @jason-crow at all?

I am touching base with him before this merges in.

**Review by pmconne — APPROVED** [review]
I don't think we should be precompiling shaders for tests, but I don't know a generic way to enforce that.

**Comment by markschlosseratbentley** [comment]
> I don't think we should be precompiling shaders for tests, but I don't know a generic way to enforce that.

I agree. I think we should try to look into this at some point.

**Pull request merged**
