### PR TITLE
accept linux filepaths (frontslash)

### PR DESCRIPTION
**Pull request by alarkbentley**
The new CopyStaticAssetsPlugin did not work on linux machines because it assumes windows type filepaths (backslash).

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]
thanks for fixing this, didnt think about linux when originally writing the regex

**Review by calebmshafer — APPROVED** [review]
LGTM. Just validated the fix on MacOS.

@SaemJeon can you check and see if the test suite you're working on for webpack could catch this issue going forward? Not something we need to do in this PR but once your PR is done we should add one.

**Comment by calebmshafer** [comment]
@alarkbentley can you run `rush change`?

**Comment by alarkbentley** [comment]
> @alarkbentley can you run `rush change`?

done

**Comment by calebmshafer** [comment]
@Mergifyio backport release/2.16.x

**Pull request merged**
