### PR TITLE
Menu item disabled fix

### PR DESCRIPTION
**Pull request by tuncb**
Fix isDisabled property behavior when context menus are created through menuitems

* Propagate isdisabled menuitem property to contextmenuitem disabled property
* Fix calling of onclick and onSelect calls when ContextMenuItem is disabled

### CODE REVIEW

**Review by GerardasB — APPROVED** [review]

**Review by DanEastBentley — APPROVED** [review]

**Review by calebmshafer — DISMISSED** [review]
@tuncb can you run `rush change` and add a description of the change to the changelog? This is currently blocking the build.

**Comment by tuncb** [comment]
@calebmshafer Thanks for the reminder, added documentation

**Comment by tuncb** [comment]
@calebmshafer Could you review the changes you requested? Is there anything else I should do?

**Review by bsteinbk — APPROVED** [review]

**Comment by calebmshafer** [comment]
@tuncb queued a new set of builds and the test suites are failing in ui-core and ui-framework due to the drop in code coverage.  Everything else succeeded however.

```
--[ FAILURE: @bentley/ui-core ]--------------------[ 5 minutes 10.0 seconds ]--

ERROR: Coverage for lines (99.97%) does not meet global threshold (100%)
ERROR: Coverage for branches (99.95%) does not meet global threshold (100%)
ERROR: Coverage for statements (99.97%) does not meet global threshold (100%)

--[ FAILURE: @bentley/ui-framework ]---------------[ 5 minutes 10.0 seconds ]--

ERROR: Coverage for branches (99.98%) does not meet global threshold (100%)
```

**Review by calebmshafer — CHANGES_REQUESTED** [review]
@tuncb queued a new set of builds and the test suites ui-core and ui-framework are failing due to the drop in code coverage.  Everything else succeeded.

Mind taking a look at adding a few more tests to get the coverage up?

```
--[ FAILURE: @bentley/ui-core ]--------------------[ 5 minutes 10.0 seconds ]--

ERROR: Coverage for lines (99.97%) does not meet global threshold (100%)
ERROR: Coverage for branches (99.95%) does not meet global threshold (100%)
ERROR: Coverage for statements (99.97%) does not meet global threshold (100%)

--[ FAILURE: @bentley/ui-framework ]---------------[ 5 minutes 10.0 seconds ]--

ERROR: Coverage for branches (99.98%) does not meet global threshold (100%)
```

**Review by calebmshafer — APPROVED** [review]

**Pull request merged**
