### PR TITLE
Addon 2.10.2

### PR DESCRIPTION
**Pull request by pmconne**

### CODE REVIEW

**Comment by pmconne** [comment]
@calebmshafer I'll need your superpowers to bypass squash when this is ready to complete.

**Review by hnn0003 — APPROVED** [review]

**Review by DStradley — APPROVED** [review]

**Review by RBBentley — APPROVED** [review]

**Review by EarlinLutz — APPROVED** [review]

**Review by mgooding — APPROVED** [review]

**Review by kabentley — APPROVED** [review]

**Comment by calebmshafer** [comment]
@kabentley do your recent changes require Node 10.17?  Looks like the integration tests are failing on Node 10.16.

**Comment by pmconne** [comment]
> @kabentley do your recent changes require Node 10.17? Looks like the integration tests are failing on Node 10.16.
> 
> Edit: It looks like it's only presentation tests failing. @grigasp

The test errs in loading the native platform, complaining about napi_is_date, which was indeed introduced in node 10.17.
@kabentley was it your intention to move minimum node version from 10.16 to 10.17?
https://nodejs.org/api/n-api.html#n_api_napi_is_date

**Comment by kabentley** [comment]
Yes, I changed the minimum version of Node to 10.17. I told @calebmshafer about this (on your Node 14 branch.)  I guess I somehow lost the change when I had to cherry-pick to the new branch.

**Comment by calebmshafer** [comment]
@kabentley sounds good.  I just updated the rest of the package.json files and the builds. I'll leave the update to the NextVersion.md for my Node 14 PR.  Hoping to wrap that up early next week.

**Review by calebmshafer — APPROVED** [review]

**Review by bsteinbk — APPROVED** [review]

**Review by grigasp — APPROVED** [review]

**Review by ColinKerr — APPROVED** [review]

**Review by c-macdonald — APPROVED** [review]

**Review by diegoalexdiaz — APPROVED** [review]

**Review by swwilson-bsi — APPROVED** [review]

**Review by scsewall — APPROVED** [review]

**Review by abeesh — APPROVED** [review]

**Review by ramanujam-raman — APPROVED** [review]

**Review by wgoehrig — APPROVED** [review]

**Pull request merged**
