### PR TITLE
Remove deprecated config-loader

### PR DESCRIPTION
**Pull request by SpencerWBarnes**
Delete config-loader package and replace with a simplified local function with a dotenv call

### CODE REVIEW

**Comment by SpencerWBarnes** [comment]
@Mergifyio update

**Review by pmconne — APPROVED** [review]
Not in love with the all the copy-paste but seems preferable to keeping the separate package.

**Review by calebmshafer — APPROVED** [review]

**Comment by aruniverse** [comment]
@SpencerWBarnes any reason we dint bump to the latest? 
dotenv@10.0.0 
https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md

**Comment by calebmshafer** [comment]
@aruniverse good question, no particular reason.  @SpencerWBarnes mind bumping all dependencies in the repo to the latest dotenv version?

**Comment by SpencerWBarnes** [comment]
@calebmshafer can do. Thanks for noticing that @aruniverse

**Comment by aruniverse** [comment]
Might i add we look into using [dotenv-flow](https://www.npmjs.com/package/dotenv-flow)?
We could then commit default env vars to the .env and track in vcs, and then just override accordingly in a `.env.*.local` file.

I know `dotenv` recommend not commit .env files but dotenv-flow suggest otherwise, and this is the approach taken by main big names, like react-scripts and others.

**Pull request merged**
