### PR TITLE
Presentation: Highlight GroupInformationElement members

### PR DESCRIPTION
**Pull request by grigasp**
- Change deprecated rules to newer replacements.
- Highlight members of `BisCore.GroupInformationElement`

### CODE REVIEW

**Review by saskliutas — APPROVED** [review]

**Review by pmconne — APPROVED** [review]

**Comment by grigasp** [comment]
The documentation build fails on something unrelated to my changes. @calebmshafer, @williamkbentley, can you please have a look?

**Comment by pmconne** [comment]
> The documentation build fails on something unrelated to my changes. @calebmshafer, @williamkbentley, can you please have a look?

Those are from #754 merged by @RBBentley yesterday. That PR's [docs build](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=756008&view=logs&j=00af5505-930d-50dd-3844-b167e8b4bb13&t=e41c6f8c-503e-58b5-343c-c4aff92c601d) is full of "module not found" errors - it appears to think it succeeded.

@grigasp do you want these fixed on your branch or in separate PR?

**Comment by grigasp** [comment]
> > The documentation build fails on something unrelated to my changes. @calebmshafer, @williamkbentley, can you please have a look?
> 
> Those are from #754 merged by @RBBentley yesterday. That PR's [docs build](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=756008&view=logs&j=00af5505-930d-50dd-3844-b167e8b4bb13&t=e41c6f8c-503e-58b5-343c-c4aff92c601d) is full of "module not found" errors - it appears to think it succeeded.
> 
> @grigasp do you want these fixed on your branch or in separate PR?

Probably separate PR to make this one cleaner.

**Comment by pmconne** [comment]
> Probably separate PR to keep this one clean

#806

**Pull request merged**
