### PR TITLE
Tweak code owners

### PR DESCRIPTION
**Pull request by pmconne**
Establish areas of code covered by display team. Add @bbastings for markup.

### CODE REVIEW

**Review by mgooding — APPROVED** [review]

**Comment by pmconne** [comment]
@calebmshafer should I expect the required reviewers on this PR to account for my changes to CODEOWNERS?

**Comment by calebmshafer** [comment]
> @calebmshafer should I expect the required reviewers on this PR to account for my changes to CODEOWNERS?

@pmconne no, the codeowners for this PR will be based on what's on `master` and only take effect once it's merged.

**Comment by pmconne** [comment]
> > @calebmshafer should I expect the required reviewers on this PR to account for my changes to CODEOWNERS?
> 
> @pmconne no, the codeowners for this PR will be based on what's on `master` and the changes here will only take effect once it's merged.

Thanks. Are you good with these changes?

**Review by scsewall — APPROVED** [review]

**Review by calebmshafer — APPROVED** [review]

**Comment by pmconne** [comment]
@calebmshafer gonna make a separate branch; this PR has gotten out of sync with ADO.

**Comment by pmconne** [comment]
https://github.com/imodeljs/imodeljs/pull/410

**Pull request closed without merging**
