### PR TITLE
Support for editing standalone files in Electron ui-test-app

### PR DESCRIPTION
**Pull request by DanEastBentley**

### CODE REVIEW

**Comment by kabentley** [comment]
Dan, do you also want to make this work in the web app? If so, see the startup code in display-test-app:

src>frontend>App.ts:
     `await LocalhostIpcApp.startup(opts);`

src>backend>Backend.ts:
    `await LocalhostIpcHost.startup({ iModelHost });`

in place of your current calls to WebViewerApp.startup and IModelHost.startup

**Comment by DanEastBentley** [comment]
Keith,
I got the following errors with your suggested changes:

LocalhostIpcApp.ts:20 WebSocket connection to 'ws://localhost:3002/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
LocalTransport @ LocalhostIpcApp.ts:20
main.chunk.js:27405 Info    |ui-test-app.LocalFileSupport| openLocalFile: Opening standalone or snapshot. path=e:\bim\imodeljs/04_Plant-editable.bim writable=true
LocalhostIpcApp.ts:29 WebSocket is already in CLOSING or CLOSED state.
send @ LocalhostIpcApp.ts:29

There must be other changes required. We can work on those in another PR.

**Review by bsteinbk — APPROVED** [review]

**Comment by kabentley** [comment]
> There must be other changes required. We can work on those in another PR.

Ok, probably going to need @swbsi to help with this when you want to try it.

**Pull request merged**
